/**
 * @file element_solid.h
 * @brief Declares the common three-dimensional solid element formulation.
 *
 * `SolidElement` provides reference/current geometry, material evaluation,
 * strain-displacement operators and the common linear, prestressed and
 * Total-Lagrangian nonlinear assembly used by the concrete C3D solid topologies.
 *
 * Every constitutive integration point is associated with one globally
 * enumerated material-point row. State-neutral operators read the committed row
 * without producing a persistent target state. Mechanical evaluations with
 * update_state=true read committed history and write the corresponding trial row.
 *
 * @author Finn Eggers
 * @date 07.08.2026
 */

#pragma once

#include "../../material/strain/volume_strain_green_lagrange.h"
#include "../../material/stress/volume_stress_cauchy.h"
#include "../../material/stress/volume_stress_pk2.h"
#include "../element/element_structural.h"
#include "../element/element_thermal.h"
#include "../geometry/surface/surface.h"

#include <array>
#include <functional>

namespace fem::model {

/**
 * @brief Common base for three-dimensional continuum elements.
 *
 * Concrete solid elements provide topology-specific interpolation and
 * quadrature. The base implements geometry transformations, constitutive
 * evaluation and the common structural operators. `evaluate()` always uses
 * Total-Lagrangian kinematics at the supplied linearization state u0, with a null
 * state denoting u0 = 0. It independently assembles the requested internal force,
 * the complete tangent at u0, and the geometric stiffness generated by the
 * linearized stress increment from u0 to the requested displacement state u.
 *
 * Stress is kept local to the element evaluation. No global integration-point
 * stress scratch field is required for geometric stiffness or nonlinear force
 * assembly. Persistent constitutive history consists only of committed and trial
 * material-state rows.
 */
template<Index N>
struct SolidElement : StructuralElement, ThermalElement{
    // Spatial dimension and engineering-Voigt strain size
    static constexpr Dim D        = 3;
    static constexpr Dim n_strain = 6;

    // Global connectivity in the topology shape-function order
    std::array<ID, N> node_ids {};

protected:
    // Topology-specific reference-space recovery from constitutive integration
    // points to element nodes. Concrete solids cache this constant matrix.
    virtual const RowMatrix& extrapolation_matrix() = 0;

public:
    // Construct the persistent connectivity; the model supplies section and field bindings
    SolidElement(ID elem_id, std::array<ID, N> node_ids)
        : StructuralElement(elem_id),
          node_ids         (node_ids) {}

    ~SolidElement() override = default;

    ElDofs    dofs() const override;
    Dim       dimensions() const override;
    Dim       n_nodes() const override;
    Dim       num_ip() const override;
    const ID* nodes() const override;
    bool      is_solid() const override { return true; }

    SurfacePtr surface(ID surface_id) override = 0;

    // Element geometry and interpolation. Concrete topologies define natural
    // node coordinates, shape functions and quadrature; the base gathers
    // reference/current global coordinates from ModelData.
    virtual StaticMatrix<N, D> node_coords_local() = 0;
    virtual StaticMatrix<N, D> node_coords_reference();
    virtual StaticMatrix<N, D> node_coords_current();

    virtual StaticMatrix<N, 1> shape_function(Precision r, Precision s, Precision t)   = 0;
    virtual StaticMatrix<N, D> shape_derivative(Precision r, Precision s, Precision t) = 0;

    virtual const math::quadrature::Quadrature& integration_scheme() const = 0;
    virtual const math::quadrature::Quadrature& integration_scheme_stiffness() const {
        return integration_scheme();
    }

    // Resolve the assigned solid section and the optional element-level material
    // rotation/stiffness scale used by every constitutive evaluation.
    SolidSection* get_section();

    Mat3      additional_material_rotation() const;
    Precision element_stiffness_scale() const;
    Vec3      material_position_reference(Precision r, Precision s, Precision t);

    // Evaluate the zero-Green-Lagrange material tangent at one natural point.
    // A null new_state requests a state-neutral auxiliary constitutive query.
    Mat6 material_tangent_reference(
        Precision        r,
        Precision        s,
        Precision        t,
        const Precision* old_state,
        Precision*       new_state);

    // Evaluate Total-Lagrangian PK2 stress and optional dS/dE in global
    // reference coordinates with the same state-pointer and scaling contract.
    // A null tangent skips constitutive tangent construction when supported
    // by the material, including residual-only assembly and recovery.
    void evaluate_material(
        Precision                        r,
        Precision                        s,
        Precision                        t,
        const VolumeStrainGreenLagrange&  global_strain,
        const Precision*                 old_state,
        Precision*                       new_state,
        VolumeStressPK2&                 global_stress,
        Mat6*                            global_tangent);

    // Interpolate element-local nodal values at natural coordinates. The data
    // rows use the same ordering as the topology shape functions.
    template<Dim K>
    StaticVector<K> interpolate(
        StaticMatrix<N, K> data,
        Precision          r,
        Precision          s,
        Precision          t);

    // Gather global nodal field components in connectivity order, optionally
    // selecting a component offset and stride.
    template<Dim K>
    StaticMatrix<N, K> nodal_data(
        const Field& full_data,
        Index        offset = 0,
        Index        stride = 1);

    // Geometric mappings. Jacobian rows follow natural directions; F maps
    // reference global vectors into the current global configuration.
    StaticMatrix<D, D> jacobian(
        const StaticMatrix<N, D>& node_coords,
        Precision                 r,
        Precision                 s,
        Precision                 t);

    Mat3 deformation_gradient(
        const StaticMatrix<N, D>& reference_coords,
        const StaticMatrix<N, D>& current_coords,
        Precision                 r,
        Precision                 s,
        Precision                 t);

    // Engineering-Voigt strain operators in node-major XYZ ordering. Reference
    // gradients supply both infinitesimal and Total-Lagrangian kinematics.
    StaticMatrix<n_strain, D * N> strain_displacement(const StaticMatrix<N, D>& shape_der_global);
    StaticMatrix<N, D> shape_derivatives_reference(
        const StaticMatrix<N, D>& reference_coords,
        Precision                 r,
        Precision                 s,
        Precision                 t,
        Precision&                det,
        bool                      check_det = true
    );
    StaticMatrix<n_strain, D * N> green_lagrange_strain_displacement(
        const StaticMatrix<N, D>& dN_dX,
        const Mat3&               F
    );

    // Total-Lagrangian state evaluation. target_* defines (u,T), while base_*
    // defines the linearization state (u0,T0). The complete tangent is evaluated
    // at the base state and supplies the displacement-linearized continuation
    // from the exact force anchor at (u0,T).
    MapMatrix evaluate(
        Precision*   tangent,
        Precision*   geometric_tangent,
        NodeData*    internal_force,
        const Field* target_displacement,
        const Field* target_temperature,
        const Field* base_displacement,
        const Field* base_temperature,
        bool         update_state
    ) override;
    MapMatrix mass(Precision* buffer) override;

    // Scalar-temperature operators integrated in the reference configuration
    MapMatrix conductivity(Precision* buffer) override;
    MapMatrix capacity(Precision* buffer) override;

    // Signed physical volume of the current model configuration
    Precision volume() override;

    // Stress/strain recovery coordinates
    RowMatrix stress_strain_nodal_rst() override;
    RowMatrix stress_strain_ip_rst() override;

    // Integrate distributed fields over current model volume, optionally with
    // density scaling. The force overload scatters consistent nodal contributions.
    Precision integrate_scalar_field(
        bool               scale_by_density,
        const ScalarField& field) override;
    Vec3      integrate_vector_field(
        bool            scale_by_density,
        const VecField& field) override;
    void      integrate_vector_field(
        Field&          node_loads,
        bool            scale_by_density,
        const VecField& field) override;
    Mat3      integrate_tensor_field(
        bool            scale_by_density,
        const TenField& field) override;

    // Convert the current model temperature into equivalent forces or scalar
    // nodal free strain. The material owns the stress-free zero temperature.

    // Stress/strain recovery is state-neutral. Constitutive response is evaluated
    // only at material integration points; nodal output is extrapolated from the
    // corresponding integration-point values in natural coordinates.
    // Linearize strain and Cauchy stress about the supplied displacement state.
    // Null denotes zero; passing displacement itself recovers the exact response.
    void compute_stress_strain(
        Field*           strain,
        Field*           stress,
        const Field&     displacement,
        const RowMatrix& rst,
        int              offset,
        const Field*     linearization) override;
    bool compute_peeq(
        Field& peeq,
        int    offset) override;
    void compute_compliance(
        Field& displacement,
        Field& result) override;
    void compute_compliance_angle_derivative(
        Field& displacement,
        Field& result) override;
    void compute_heat_flux(
        Field&       heat_flux,
        const Field& temperature) override;
};

} // namespace fem::model

#include "element_solid_compute.ipp"
#include "element_solid_load.ipp"
#include "element_solid_metadata.ipp"
#include "element_solid.ipp"
