/**
 * @file element_solid_load.ipp
 * @brief Implements thermal loading and distributed-field integration for solids.
 *
 * Thermal expansion is converted into an equivalent nodal load by integrating
 * the reference material tangent against isotropic thermal strain. Auxiliary
 * load quadrature points reuse the closest constitutive integration-point state
 * row so every material call follows the same explicit state interface.
 *
 * The remaining routines integrate scalar, vector and tensor fields over the
 * current solid volume, optionally including material density.
 *
 * @see SolidElement
 *
 * @author Finn Eggers
 * @date 07.08.2026
 */

#pragma once

namespace fem::model {

/**
 * Assembles the equivalent nodal load generated by isotropic thermal expansion.
 *
 * Nodal temperatures are interpolated over the element; non-finite values are
 * replaced by the supplied reference temperature. The free thermal strain
 * `alpha (T - T_ref) I` is multiplied by the zero-strain material tangent and
 * integrated through `B^T sigma_th dV`.
 *
 * Load and stiffness quadrature may differ. Each auxiliary load point therefore
 * reuses the state row of the nearest constitutive stiffness point in natural
 * coordinates. The material tangent call follows the ordinary in-place state
 * contract; no additional state storage is owned by this routine.
 *
 * @param node_loads Global nodal thermal-load field to increment.
 * @param node_temp Scalar nodal temperature field.
 * @param ref_temp Reference temperature for thermal strain and invalid values.
 */
template<Index N>
void
SolidElement<N>::apply_tload(Field& node_loads, const Field& node_temp, Precision ref_temp) {
    // Validate and collect the current geometry and scalar nodal temperatures
    StaticMatrix<N, D> node_coords_glob = this->node_coords_current();
    logging::error(node_temp.domain == FieldDomain::NODE,
                   "Temperature field '", node_temp.name, "' must be a node field");
    logging::error(node_temp.components == 1,
                   "Temperature field '", node_temp.name, "' must have 1 component");
    StaticMatrix<N, 1> node_temp_glob {};
    for (Index i = 0; i < N; ++i) {
        const Index row = static_cast<Index>(node_ids[i]);
        node_temp_glob(i) = node_temp(row, 0);
    }

    // Replace undefined temperatures by the stress-free reference temperature
    for (Index i = 0; i < (Index)node_temp_glob.size(); i++) {
        if (std::isnan(node_temp_glob(i)) || std::isinf(node_temp_glob(i))) {
            node_temp_glob(i) = ref_temp;
        }
    }

    // Validate all material data required by the thermal-stress construction
    logging::error(material() != nullptr, "no material assigned to element ", elem_id);
    logging::error(material()->has_elasticity(), "material has no elasticity components assigned at element ", elem_id);
    logging::error(material()->has_thermal_expansion(), "material has no thermal expansion assigned at element ", elem_id);

    const auto& state_scheme = this->integration_scheme_stiffness();

    // Integrate the equivalent thermal-force density over the element volume
    std::function<StaticMatrix<D*N,1>(Precision, Precision, Precision)> func =
        [this, node_coords_glob, &node_temp_glob, &ref_temp, &state_scheme](Precision r, Precision s, Precision t) -> StaticMatrix<D*N,1> {

        // Interpolate temperature and construct isotropic free thermal strain
        auto shape_func = shape_function(r, s, t);
        Precision temp = shape_func.dot(node_temp_glob);

        Precision strain_value = material()->get_thermal_expansion() * (temp - ref_temp);
        Vec6 strain{strain_value, strain_value, strain_value, 0, 0, 0};

        // Associate auxiliary quadrature points with the nearest constitutive
        // integration point so the material receives a valid history state.
        Index state_ip = 0;
        auto  state_point = state_scheme.get_point(0);
        Precision state_distance =
            (r - state_point.r) * (r - state_point.r)
            + (s - state_point.s) * (s - state_point.s)
            + (t - state_point.t) * (t - state_point.t);

        for (Index ip = 1; ip < state_scheme.count(); ++ip) {
            state_point = state_scheme.get_point(ip);
            const Precision distance =
                (r - state_point.r) * (r - state_point.r)
                + (s - state_point.s) * (s - state_point.s)
                + (t - state_point.t) * (t - state_point.t);
            if (distance < state_distance) {
                state_ip       = ip;
                state_distance = distance;
            }
        }

        Precision* state = &(*this->_model_data->material_state)(this->mp_index(state_ip), 0);

        // Convert free thermal strain to stress using the selected state-row tangent
        auto mat_matrix = material_tangent_reference(r, s, t, state);
        auto stress = mat_matrix * strain;

        // Map thermal stress to its element nodal-force contribution
        Precision det;
        auto B = strain_displacements(node_coords_glob, r, s, t, det);

        auto res = B.transpose() * stress * det;
        return res;
    };

    StaticMatrix<D*N, 1> nodal_impact = integration_scheme().integrate(func);

    // Scatter the integrated translational force into global nodal storage
    ID local_id = 0;
    for (auto n_id : node_ids) {
        node_loads(n_id, 0) += nodal_impact(local_id * 3 + 0);
        node_loads(n_id, 1) += nodal_impact(local_id * 3 + 1);
        node_loads(n_id, 2) += nodal_impact(local_id * 3 + 2);
        local_id++;
    }
}


//-----------------------------------------------------------------------------
// integrate_scalar_field / integrate_vector_field / integrate_tensor_field
//-----------------------------------------------------------------------------
template<Index N>
Precision
SolidElement<N>::integrate_scalar_field(bool scale_by_density,
                                        const ScalarField& field)
{
    // Node coordinates
    StaticMatrix<N, D> node_coords_glob = this->node_coords_current();

    // Optional density scaling
    Precision rho = 1.0;
    if (scale_by_density) {
        auto mat = this->material();
        logging::error(mat != nullptr && mat->has_density(),
                       "SolidElement: material density is required when scale_by_density=true for element ", this->elem_id);
        rho = mat->get_density();
    }

    Precision result = Precision(0);
    const auto& scheme = this->integration_scheme();
    for (Index ip = 0; ip < scheme.count(); ++ip) {
        const auto pt = scheme.get_point(ip);
        const Precision r = pt.r;
        const Precision s = pt.s;
        const Precision t = pt.t;
        const Precision w = pt.w;

        StaticMatrix<N, 1> Nvals = this->shape_function(r, s, t);
        const StaticMatrix<D, D> J = this->jacobian(node_coords_glob, r, s, t);
        const Precision detJ = J.determinant();

        Vec3 x_ip = Vec3::Zero();
        for (Index i = 0; i < N; ++i) x_ip += Nvals(i) * node_coords_glob.row(i);

        result += field(x_ip) * (rho * w * detJ);
    }
    return result;
}

template<Index N>
Vec3
SolidElement<N>::integrate_vector_field(bool scale_by_density,
                                        const VecField& field)
{
    // Node coordinates
    StaticMatrix<N, D> node_coords_glob = this->node_coords_current();

    Precision rho = 1.0;
    if (scale_by_density) {
        auto mat = this->material();
        logging::error(mat != nullptr && mat->has_density(),
                       "SolidElement: material density is required when scale_by_density=true for element ", this->elem_id);
        rho = mat->get_density();
    }

    Vec3 result = Vec3::Zero();
    const auto& scheme = this->integration_scheme();
    for (Index ip = 0; ip < scheme.count(); ++ip) {
        const auto pt = scheme.get_point(ip);
        const Precision r = pt.r;
        const Precision s = pt.s;
        const Precision t = pt.t;
        const Precision w = pt.w;

        StaticMatrix<N, 1> Nvals = this->shape_function(r, s, t);
        const StaticMatrix<D, D> J = this->jacobian(node_coords_glob, r, s, t);
        const Precision detJ = J.determinant();

        Vec3 x_ip = Vec3::Zero();
        for (Index i = 0; i < N; ++i) x_ip += Nvals(i) * node_coords_glob.row(i);

        result += field(x_ip) * (rho * w * detJ);
    }
    return result;
}

template<Index N>
void
SolidElement<N>::integrate_vector_field(Field& node_loads,
                                        bool scale_by_density,
                                        const VecField& field)
{
    // Node coordinates
    StaticMatrix<N, D> node_coords_glob = this->node_coords_current();

    // Optional density scaling
    Precision rho = 1.0;
    if (scale_by_density) {
        auto mat = this->material();
        logging::error(mat != nullptr && mat->has_density(),
                       "SolidElement: material density is required when scale_by_density=true for element ", this->elem_id);
        rho = mat->get_density();
    }

    const auto& scheme = this->integration_scheme();
    for (Index ip = 0; ip < scheme.count(); ++ip) {
        const auto pt = scheme.get_point(ip);
        const Precision r = pt.r;
        const Precision s = pt.s;
        const Precision t = pt.t;
        const Precision w = pt.w;

        StaticMatrix<N, 1> Nvals = this->shape_function(r, s, t);
        const StaticMatrix<D, D> J = this->jacobian(node_coords_glob, r, s, t);
        const Precision detJ = J.determinant();

        Vec3 x_ip = Vec3::Zero();
        for (Index i = 0; i < N; ++i) x_ip += Nvals(i) * node_coords_glob.row(i);

        Vec3 f_ip = field(x_ip) * (rho * w * detJ);

        for (Index i = 0; i < N; ++i) {
            const ID n_id = this->node_ids[i];
            const Precision a = Nvals(i);
            node_loads(n_id, 0) += a * f_ip(0);
            node_loads(n_id, 1) += a * f_ip(1);
            node_loads(n_id, 2) += a * f_ip(2);
        }
    }
}

template<Index N>
Mat3
SolidElement<N>::integrate_tensor_field(bool scale_by_density,
                                        const TenField& field)
{
    // Node coordinates
    StaticMatrix<N, D> node_coords_glob = this->node_coords_current();

    Precision rho = 1.0;
    if (scale_by_density) {
        auto mat = this->material();
        logging::error(mat != nullptr && mat->has_density(),
                       "SolidElement: material density is required when scale_by_density=true for element ", this->elem_id);
        rho = mat->get_density();
    }

    Mat3 result = Mat3::Zero();
    const auto& scheme = this->integration_scheme();
    for (Index ip = 0; ip < scheme.count(); ++ip) {
        const auto pt = scheme.get_point(ip);
        const Precision r = pt.r;
        const Precision s = pt.s;
        const Precision t = pt.t;
        const Precision w = pt.w;

        StaticMatrix<N, 1> Nvals = this->shape_function(r, s, t);
        const StaticMatrix<D, D> J = this->jacobian(node_coords_glob, r, s, t);
        const Precision detJ = J.determinant();

        Vec3 x_ip = Vec3::Zero();
        for (Index i = 0; i < N; ++i) x_ip += Nvals(i) * node_coords_glob.row(i);

        result += field(x_ip) * (rho * w * detJ);
    }
    return result;
}

}  // namespace fem::model
