/**
 * @file nonlinear_state_manager.cpp
 * @brief Implements nonlinear material and contact state management.
 *
 * Material history is represented by committed and trial material-point fields.
 * Contact history remains inside each contact object and is coordinated here so
 * nonlinear load cases do not need to traverse or manipulate contact state
 * directly.
 *
 * @see NonlinearStateManager
 * @see constraint::Contact
 *
 * @author Finn Eggers
 * @date 07.08.2026
 */

#include "nonlinear_state_manager.h"

#include "../../model/model.h"

#include <utility>

namespace fem {
namespace loadcase {
namespace tools {

/**
 * Creates the material history buffers required by the materials assigned to
 * the current model.
 *
 * The committed field is initialized from the constitutive material definitions.
 * The active trial field is then reconstructed from that committed history and
 * exposed through `ModelData::material_state`. Stateless models allocate no
 * material fields; contact state remains available independently.
 *
 * @param model Model whose nonlinear material and contact state is managed.
 */
NonlinearStateManager::NonlinearStateManager(model::Model& model)
    : model_(model),
      previous_material_state_(model._data->material_state) {
    // Stateless models retain the default material-state binding and require no
    // solver-owned history buffers
    const Index state_size = model_.maximum_material_state_size();
    if (state_size == 0) {
        return;
    }

    // Allocate accepted and active buffers with the common state-row width
    committed_material_state_ = model_._data->create_field(
        "MATERIAL_STATE_COMMITTED",
        model::FieldDomain::ELEMENT_MP,
        state_size,
        false,
        false
    );

    trial_material_state_ = model_._data->create_field(
        "MATERIAL_STATE",
        model::FieldDomain::ELEMENT_MP,
        state_size,
        false,
        false
    );

    // Initialize accepted history from each constitutive model, then expose an
    // identical trial copy for the first nonlinear evaluation
    model_.initialize_material_state(*committed_material_state_);
    reset_material_state();
}

/**
 * Restores the material-state binding that existed before this nonlinear solve.
 *
 * The committed and trial fields are solver-owned temporary storage and disappear
 * with the manager. Only the previous `ModelData::material_state` binding is
 * restored; contact runtime state remains owned by the contact objects.
 */
NonlinearStateManager::~NonlinearStateManager() {
    model_._data->material_state = previous_material_state_;
}

/**
 * Reconstructs the active material state from the last accepted increment.
 *
 * Constitutive updates operate in place on `ModelData::material_state`. Newton
 * iterations and line-search candidates are only alternative evaluations of the
 * same physical increment, so none may inherit material history generated by a
 * previous candidate. Copying the committed field before each independent
 * evaluation enforces that invariant.
 */
void NonlinearStateManager::reset_material_state() {
    // A missing committed buffer denotes an entirely stateless model
    if (!committed_material_state_) {
        return;
    }

    // Every independent residual or tangent evaluation starts from the last
    // accepted increment rather than from another candidate's in-place updates
    trial_material_state_->values = committed_material_state_->values;
    bind_material_state();
}

/**
 * Accepts the material history generated by the converged nonlinear increment.
 *
 * The current trial buffer becomes the new committed history. The other buffer
 * is immediately synchronized with it and rebound as the active trial field so
 * later postprocessing or the next increment starts from the accepted state.
 */
void NonlinearStateManager::commit_material_state() {
    // A missing committed buffer denotes an entirely stateless model
    if (!committed_material_state_) {
        return;
    }

    // Promote the converged buffer without copying, then synchronize the spare
    // buffer for postprocessing and the next trial evaluation
    std::swap(committed_material_state_, trial_material_state_);
    trial_material_state_->values = committed_material_state_->values;
    bind_material_state();
}

/**
 * Opens one contact trial in which partner ownership may be updated once.
 *
 * This mode is used when entering an increment and when refreshing the contact
 * active set after Newton convergence. Contact determines partners during the
 * first assembly in the trial and freezes them for subsequent assemblies.
 */
void NonlinearStateManager::begin_contact_update_trial() {
    // Apply one consistent outer-trial policy to every contact definition
    for (const auto& contact : model_._data->contacts) {
        contact.begin_update_trial();
    }
}

/**
 * Opens one nested contact trial with the current partner ownership frozen.
 *
 * Predictor and line-search evaluations must not alter the discrete contact
 * problem selected by their parent state. Natural contact coordinates may still
 * be reprojected on the already selected master surface.
 */
void NonlinearStateManager::begin_contact_frozen_trial() {
    // Nested predictor and line-search trials inherit fixed discrete ownership
    for (const auto& contact : model_._data->contacts) {
        contact.begin_frozen_trial();
    }
}

/**
 * Accepts the current contact trial for every contact in the model.
 *
 * Nested trials are promoted to their parent trial; an outermost accepted trial
 * becomes the committed contact runtime state.
 */
void NonlinearStateManager::commit_contact_trial() {
    // Promote each contact child state at the same transaction boundary
    for (const auto& contact : model_._data->contacts) {
        contact.commit_trial();
    }
}

/**
 * Discards the current contact trial for every contact in the model.
 *
 * The parent trial or committed contact state remains unchanged, which allows
 * rejected predictors, line-search candidates and complete increment attempts to
 * leave no persistent contact history behind.
 */
void NonlinearStateManager::rollback_contact_trial() {
    // Restore every contact to its parent state at the same transaction boundary
    for (const auto& contact : model_._data->contacts) {
        contact.rollback_trial();
    }
}

/**
 * Updates the discrete and augmented contact state after Newton convergence.
 *
 * The caller must first open an update trial and assemble the converged geometry.
 * Partner-signature changes detect a different discrete contact problem, while
 * the augmented-Lagrange update changes normal multipliers when the converged gap
 * still requires augmentation. Either change requires another Newton solve at
 * the same path-control state.
 *
 * @return `true` if neither partner ownership nor multipliers changed.
 */
bool NonlinearStateManager::update_contact_active_set() {
    bool changed = false;

    // Combine discrete partner and multiplier changes across all contacts
    for (const auto& contact : model_._data->contacts) {
        const bool partner_changed    = contact.partner_signature_changed();
        const bool multiplier_changed = contact.update_augmented_lagrange();
        changed = changed || partner_changed || multiplier_changed;
    }

    return !changed;
}

/**
 * Exposes the mutable material trial buffer through the model data interface.
 *
 * Buffer names follow their current ownership so diagnostics and optional field
 * inspection continue to distinguish accepted history from the active candidate.
 */
void NonlinearStateManager::bind_material_state() {
    // Buffer names describe their current roles after pointer swapping
    committed_material_state_->name = "MATERIAL_STATE_COMMITTED";
    trial_material_state_->name     = "MATERIAL_STATE";
    model_._data->material_state    = trial_material_state_;
}

} // namespace tools
} // namespace loadcase
} // namespace fem
