/**
 * @file robin.h
 * @brief Declares Robin boundary conditions and their symbolic equation rows.
 */

#pragma once

#include "../load.h"

#include "../../core/types_num.h"
#include "../../data/field.h"

#include <memory>
#include <vector>

namespace fem::model {
struct ModelData;
}

namespace fem::bc {

/** @brief One coefficient in a symbolic Robin equation row. */
struct RobinEquationEntry {
    ID        node_id{};
    Dim       dof{};
    Precision coeff{};
};

/**
 * @brief Additive linear equation row generated by a Robin condition.
 *
 * `row_node_id,row_dof` identify the global equilibrium row to which the
 * coefficients are added. `entries` remain in nodal coordinates until Model
 * maps them to active system indices. The right-hand side is deliberately not
 * stored here: Robin conditions assemble it into the same nodal load field as
 * Neumann conditions.
 */
struct RobinEquation {
    ID                              row_node_id{};
    Dim                             row_dof{};
    std::vector<RobinEquationEntry> entries{};
};

using RobinEquations = std::vector<RobinEquation>;

/**
 * @brief Boundary condition producing a RHS contribution and symbolic rows.
 */
struct Robin : Load {
    using Ptr = std::shared_ptr<Robin>;

    virtual ~Robin() = default;

    virtual void apply(model::ModelData& model_data,
                       model::Field&     rhs,
                       RobinEquations&   equations,
                       Precision         time,
                       bool              ignore_amplitude = false) = 0;
};

} // namespace fem::bc
