/**
 * @file test_shell_inclined_director.cpp
 * @brief Regression tests for transverse shear with inclined shell directors.
 */

#include "../src/model/shell/frt_shell_s4.h"

#include <gtest/gtest.h>

#include <array>
#include <cmath>

namespace {

using Shell = fem::model::FRTShellS4;

Shell::ReferencePoint inclined_reference_point() {
    Shell::ReferencePoint point;
    point.invJ.setIdentity();
    point.basis.setIdentity();
    point.D = fem::Vec3(0.0, 1.0, 2.0).normalized();
    return point;
}

} // namespace

TEST(ShellInclinedDirector, PureMembraneStrainDoesNotBecomeTransverseShear) {
    Shell shell(0, std::array<fem::ID, 4>{0, 1, 2, 3});
    const auto point = inclined_reference_point();

    Shell::Vec8 strain = Shell::Vec8::Zero();
    const fem::Precision epsilon_yy = 0.1;
    const fem::Precision d2 = point.D(1);

    // Covariant gamma_bD generated by a pure E22 membrane strain when the
    // reference director has a tangential e2 component.
    strain(1) = epsilon_yy;
    strain(7) = 2.0 * d2 * epsilon_yy;

    shell.transform_strain_to_local(point, strain);

    EXPECT_NEAR(strain(1), epsilon_yy, 1e-14);
    EXPECT_NEAR(strain(6), 0.0, 1e-14);
    EXPECT_NEAR(strain(7), 0.0, 1e-14);
}

TEST(ShellInclinedDirector, RecoversOrthonormalEngineeringShear) {
    Shell shell(0, std::array<fem::ID, 4>{0, 1, 2, 3});
    const auto point = inclined_reference_point();

    Shell::Vec8 strain = Shell::Vec8::Zero();
    const fem::Precision epsilon_yy = 0.1;
    const fem::Precision gamma_23 = 0.07;
    const fem::Precision d2 = point.D(1);
    const fem::Precision d3 = point.D(2);

    strain(1) = epsilon_yy;
    strain(7) = 2.0 * d2 * epsilon_yy + d3 * gamma_23;

    shell.transform_strain_to_local(point, strain);

    EXPECT_NEAR(strain(7), gamma_23, 1e-14);
}

TEST(ShellInclinedDirector, AppliesSameDeskewingToBMatrix) {
    Shell shell(0, std::array<fem::ID, 4>{0, 1, 2, 3});
    const auto point = inclined_reference_point();

    Shell::Vec8 strain = Shell::Vec8::Zero();
    Shell::Mat8x6N B = Shell::Mat8x6N::Zero();

    const fem::Precision d2 = point.D(1);
    B(1, 4) = 0.25;
    B(7, 4) = 2.0 * d2 * B(1, 4);

    shell.transform_strain_to_local(point, strain, &B);

    EXPECT_NEAR(B(1, 4), 0.25, 1e-14);
    EXPECT_NEAR(B(7, 4), 0.0, 1e-14);
}

TEST(ShellInclinedDirector, DeskewPullbackPreservesVirtualWork) {
    Shell shell(0, std::array<fem::ID, 4>{0, 1, 2, 3});
    const auto point = inclined_reference_point();
    const Shell::Mat8 transform = shell.director_deskew_transform(point);

    Shell::Vec8 covariant_strain;
    covariant_strain << 0.03, -0.02, 0.01, 0.04, -0.05, 0.02, 0.06, -0.07;

    Shell::Vec8 local_resultants;
    local_resultants << 3.0, -2.0, 1.5, 0.7, -0.8, 0.4, 5.0, -4.0;

    const fem::Precision local_work =
        local_resultants.dot(transform * covariant_strain);
    const fem::Precision pulled_back_work =
        (transform.transpose() * local_resultants).dot(covariant_strain);

    EXPECT_NEAR(local_work, pulled_back_work, 1e-14);
}
