/**
 * @file instance.h
 * @brief Defines placement and compiled identifier mappings of one part instance.
 *
 * An `Instance` references one reusable part definition together with a rigid
 * translation and rotation. It does not duplicate nodes, elements, sets,
 * surfaces or sections. These entities remain owned by the referenced `Part`
 * and are expanded once by `Model::compile()` into solver-facing dense topology.
 *
 * Instances are retained through compilation in the semantic dictionary owned
 * by `ModelData`; the concrete type is only included and operated by `Model`.
 *
 * The transformation maps local part coordinates to assembled global
 * coordinates according to
 *
 * \f[
 *     \boldsymbol x = \boldsymbol R\,\boldsymbol X + \boldsymbol t.
 * \f]
 *
 * @see Part
 * @see Model
 * @see ModelData
 *
 * @author Finn Eggers
 * @date 19.08.2026
 */

#pragma once

#include "../core/types_eig.h"
#include "../data/namable.h"
#include "part.h"

#include <memory>
#include <string>
#include <unordered_map>
#include <utility>

namespace fem::model {

/**
 * @brief Named rigid placement of one reusable finite-element part.
 *
 * Translation and rotation are the only geometric instance-specific semantic
 * state. The four local-to-dense maps are populated by the single compile and
 * support parser/API operations that keep addressing local identifiers after the
 * semantic topology has been frozen.
 *
 * The referenced part must be valid when compilation starts. The rotation must
 * be finite, orthonormal and have determinant +1 so that element orientation and
 * surface handedness are preserved. `Model::compile()` validates these
 * invariants before creating any dense assembly entities.
 */
struct Instance : public Namable {
    // Shared ownership type used by the semantic model dictionary. Instances
    // themselves share their referenced Part instead of copying its topology.
    using Ptr = std::shared_ptr<Instance>;

    // Reusable semantic topology embedded by this instance. The part remains in
    // its own local identifier and coordinate spaces throughout compilation.
    Part::Ptr part = nullptr;

    // ID of the instance. The default instance has ID 0 while other instances increment by 1.
    ID instance_id;

    // Rigid local-to-global placement. Model compilation transforms every local
    // nodal position according to x = R X + t and rotates section directions and
    // coordinate systems consistently with the same proper rotation.
    Vec3 translation = Vec3::Zero();
    Mat3 rotation    = Mat3::Identity();

    // Local-to-dense identifier maps generated by the one-way compile pass.
    // They are empty while semantic topology is being constructed and retain the
    // final assembly identifiers afterwards so parsers and API callers can
    // resolve qualified local references without modifying the source Part.
    std::unordered_map<ID, ID> node_ids;    // local -> global
    std::unordered_map<ID, ID> element_ids; // local -> global
    std::unordered_map<ID, ID> surface_ids; // local -> global
    std::unordered_map<ID, ID> line_ids;    // local -> global

    // Construction of a named rigid placement. The referenced Part and the
    // transformation are semantic input; all identifier maps remain empty until
    // `Model::compile()` materializes this instance in the dense assembly.
    Instance(std::string name,
             Part::Ptr   part,
             Vec3        translation = Vec3::Zero(),
             Mat3        rotation    = Mat3::Identity())
        : Namable(std::move(name)),
          part       (std::move(part)),
          translation(translation),
          rotation   (rotation) {}
};

} // namespace fem::model
