/**
 * @file load_inertial.h
 * @brief Declares equivalent loads for prescribed rigid-body acceleration.
 *
 * `InertialLoad` evaluates the acceleration field generated by translation,
 * angular acceleration and angular velocity about a reference point. Structural
 * elements integrate the negative acceleration with their distributed density,
 * while optional point-mass handling adds concentrated translational and rotary
 * inertia contributions. The assembly details are implemented in
 * `load_inertial.cpp`.
 *
 * @see InertialLoad
 * @see Load
 * @see load_inertial.cpp
 * @author Finn Eggers
 * @date 06.03.2025
 */

#pragma once

#include "load.h"

#include "../data/region.h"

namespace fem {
namespace bc {

/**
 * @brief Represents a translational and rotational rigid-body inertia field.
 *
 * At position `x`, with `r = x - center_`, the prescribed acceleration is
 * `center_acc_ + alpha_ x r + omega_ x (omega_ x r)`. The applied equivalent
 * force uses the opposite sign. Structural elements supply their own density
 * and interpolation, while point-mass features can optionally be processed as
 * separate concentrated contributions.
 */
struct InertialLoad : public Load {
    // Shared ownership type for direct references to inertial loads.
    using Ptr = std::shared_ptr<InertialLoad>;

    // Global reference point from which the rotational radius vector is
    // measured.
    Vec3 center_ = {0, 0, 0};

    // Prescribed translational acceleration of the reference point.
    Vec3 center_acc_ = {0, 0, 0};

    // Prescribed angular velocity used for the centripetal acceleration and
    // gyroscopic point-mass moment.
    Vec3 omega_ = {0, 0, 0};

    // Prescribed angular acceleration used for tangential acceleration and
    // rotary-inertia moments.
    Vec3 alpha_ = {0, 0, 0};

    // Element region whose structural elements integrate the distributed mass
    // contribution.
    SPtr<model::ElementRegion> region_ = nullptr;

    // Include `PointMass` features as additional concentrated inertia terms
    // when true.
    bool consider_point_masses_ = false;

    // Construct a zero-valued, unconfigured inertial load.
    InertialLoad() = default;

    // Enable polymorphic destruction through `Load`.
    ~InertialLoad() override = default;

    // Integrate the negative rigid-body acceleration over every selected
    // structural element using density scaling. Optionally add translational
    // and rotary contributions of all point-mass features.
    void apply(model::ModelData& model_data, model::Field& bc, Precision time, bool ignore_amplitude = false) override;

    // Return the target region, reference point, translational acceleration,
    // angular kinematics and point-mass option in one diagnostic string.
    std::string str() const override;
};
} // namespace bc
} // namespace fem
