/**
 * @file support_collector.cpp
 * @brief Implements collective structural Dirichlet equation generation.
 *
 * Each stored support resolves its semantic region to global nodes and appends
 * the corresponding scalar constraint rows. The collector preserves insertion
 * order and performs no rank reduction or duplicate elimination; those algebraic
 * operations belong to the constraint-processing layer.
 *
 * @see SupportCollector
 * @see Support
 * @see constraint::Equation
 *
 * @author Finn Eggers
 * @date 17.09.2026
 */

#include "support_collector.h"

namespace fem::bc {

SupportCollector::SupportCollector(const std::string& name)
    : model::Collection<Support>(name, true, false) {}

/**
 * Builds the complete equation set generated by the stored structural supports.
 *
 * Every support appends rows of the form
 *
 *     C_i u = d_i
 *
 * to the same equation container. Direct global supports normally create one
 * nonzero coefficient per row, whereas oriented supports may create three
 * coefficients that project a global translational or rotational vector onto a
 * prescribed local axis.
 *
 * The function only collects equations. It does not inspect linear dependence,
 * eliminate constrained DOFs or alter the finite-element matrices.
 *
 * @param model_data Compiled model topology and nodal geometry used while
 *                   resolving the individual support definitions.
 * @return Concatenated constraint equations generated by all stored supports.
 */
constraint::Equations SupportCollector::get_equations(model::ModelData& model_data) {
    constraint::Equations equations{};

    // Expand every stored support into the common equation container so the
    // final row order follows the collector definition deterministically
    for (Support& support : this->_data) {
        support.apply(model_data, equations);
    }

    return equations;
}

} // namespace fem::bc
