/**
 * @file support_collector.cpp
 * @brief Implements support insertion and combined constraint generation.
 *
 * The collector stores concrete `Support` objects by value. Its overloads move
 * the selected region and coordinate-system pointers into the matching support
 * constructor, while `get_equations()` applies every stored definition to one
 * shared equation container.
 *
 * @see support_collector.h
 * @see support.cpp
 * @author Finn Eggers
 * @date 06.03.2025
 */

#include "support_collector.h"

#include <utility>

namespace fem {
namespace bc {

/**
 * Constructs a named collection of support definitions.
 *
 * Supports are stored by value and later expanded into one combined equation
 * set while preserving the collector's insertion order.
 *
 * @param name Name used to identify the support collection.
 */
SupportCollector::SupportCollector(const std::string& name)
    : model::Collection<Support>(name, true, false) {}

/**
 * Expands every stored support into one combined equation collection.
 *
 * Supports append node-level constraints in insertion order. Model topology and
 * nodal fields are forwarded so all region and coordinate-system variants are
 * resolved consistently.
 *
 * @param model_data Model topology and nodal fields.
 * @return All equations generated by this collector.
 */
constraint::Equations SupportCollector::get_equations(model::ModelData& model_data) {
    // Start from an empty container so the result contains only equations
    // generated by this support set.
    constraint::Equations equations{};

    // Each support appends its node-level equations to the same container,
    // preserving collector insertion order.
    for (Support& support : this->_data) {
        support.apply(model_data, equations);
    }

    return equations;
}

/**
 * Adds a support targeting an explicit node region.
 *
 * The region and optional coordinate system are moved into a concrete Support
 * value for later equation generation.
 *
 * @param region Target node region.
 * @param values Prescribed values for six generalized degrees of freedom.
 * @param coordinate_system Optional coordinate system for oriented constraints.
 */
void SupportCollector::add_supp(model::NodeRegion::Ptr region,
                                Vec6 values,
                                cos::CoordinateSystem::Ptr coordinate_system) {
    // Construct the support in-place and transfer ownership of the optional
    // shared pointers without an additional temporary allocation.
    this->_data.emplace_back(Support{std::move(region), values, std::move(coordinate_system)});
}

/**
 * Adds a support targeting an element region.
 *
 * The region is stored with the prescribed values and expanded to connected
 * nodes only when equations are requested.
 *
 * @param region Target element region.
 * @param values Prescribed values for six generalized degrees of freedom.
 * @param coordinate_system Optional coordinate system for oriented constraints.
 */
void SupportCollector::add_supp(model::ElementRegion::Ptr region,
                                Vec6 values,
                                cos::CoordinateSystem::Ptr coordinate_system) {
    this->_data.emplace_back(Support{std::move(region), values, std::move(coordinate_system)});
}

/**
 * Adds a support targeting a surface region.
 *
 * The region is stored with the prescribed values and expanded to connected
 * nodes only when equations are requested.
 *
 * @param region Target surface region.
 * @param values Prescribed values for six generalized degrees of freedom.
 * @param coordinate_system Optional coordinate system for oriented constraints.
 */
void SupportCollector::add_supp(model::SurfaceRegion::Ptr region,
                                Vec6 values,
                                cos::CoordinateSystem::Ptr coordinate_system) {
    this->_data.emplace_back(Support{std::move(region), values, std::move(coordinate_system)});
}
} // namespace bc
} // namespace fem
