/**
 * @file support_collector.h
 * @brief Declares named collections of polymorphic Dirichlet boundary conditions.
 *
 * Support collectors store prescribed primary variables through the common
 * `Dirichlet` interface. Structural supports and thermal temperatures may share
 * one named collector while each analysis selects only the compatible concrete
 * condition type. This preserves the existing support-set input architecture
 * without introducing a parallel thermal collector subsystem.
 *
 * Conditions remain in insertion order. Typed equation generation performs the
 * runtime filtering and delegates construction of complete algebraic equations
 * to each concrete Dirichlet condition.
 *
 * @see Dirichlet
 * @see Support
 * @see Temperature
 * @see constraint::Equation
 *
 * @author Finn Eggers
 * @date 30.08.2026
 */

#pragma once

#include "dirichlet/dirichlet.h"
#include "../data/collection.h"

#include <type_traits>

namespace fem::model {
struct ModelData;
}

namespace fem::bc {

/**
 * @brief Owns prescribed Dirichlet conditions under one collector name.
 *
 * The collector stores shared pointers to heterogeneous Dirichlet conditions in
 * insertion order. The unqualified `get_equations()` path preserves historical
 * structural behavior by selecting `Support`. The templated overload allows a
 * loadcase to request another concrete Dirichlet family, currently prescribed
 * `Temperature`, without duplicating storage or collector-selection logic.
 *
 * Typed retrieval deliberately ignores incompatible Dirichlet entries instead of
 * treating a mixed collector as an error. This permits one named support set to
 * contain structural and thermal prescriptions while the requesting analysis
 * defines which primary unknowns are relevant.
 */
struct SupportCollector : model::Collection<Dirichlet::Ptr> {
    // Shared ownership type used by the named support-collector registry in
    // `ModelData`.
    using Ptr = std::shared_ptr<SupportCollector>;

    // Expose insertion of polymorphic Dirichlet pointers through the common
    // collection base.
    using model::Collection<Dirichlet::Ptr>::add;

    // Construction creates an empty named collector while retaining the common
    // collection identity used by parser and loadcase selection.
    explicit SupportCollector(const std::string& name);
    ~SupportCollector() = default;

    // Structural compatibility path. This selects only `Support` conditions and
    // returns their equations in collector insertion order.
    constraint::Equations get_equations(model::ModelData& model_data);

    // Typed Dirichlet equation generation. Only entries dynamically matching the
    // requested concrete type are applied; incompatible conditions remain stored
    // but do not participate in this analysis-specific equation set.
    template<typename DirichletType>
    constraint::Equations get_equations(model::ModelData& model_data) {
        static_assert(std::is_base_of_v<Dirichlet, DirichletType>,
            "DirichletType must derive from Dirichlet");

        // Preserve insertion order while accumulating equations generated by all
        // matching concrete conditions.
        constraint::Equations equations{};
        for (const auto& condition : this->_data) {
            if (auto typed_condition = std::dynamic_pointer_cast<DirichletType>(condition)) {
                typed_condition->apply(model_data, equations);
            }
        }
        return equations;
    }

    // Provide read-only access to the ordered polymorphic definitions for model
    // overview and other non-mutating inspection paths.
    const std::vector<Dirichlet::Ptr>& entries() const { return this->_data; }
};

} // namespace fem::bc
