/**
 * @file load_inertial.h
 * @brief Defines equivalent loads generated by prescribed rigid-body acceleration.
 *
 * `InertialLoad` converts translational and rotational rigid-body acceleration
 * into equivalent nodal inertia forces. Distributed structural mass is handled
 * through density-scaled element integration, while concentrated point masses
 * additionally contribute direct translational force and rotary inertia moments.
 *
 * @see Condition
 * @see model::StructuralElement
 * @see model::PointElement
 * @see PointMassSection
 *
 * @author Finn Eggers
 * @date 17.09.2026
 */

#pragma once

#include "../condition.h"
#include "../../constraints/types/equation.h"
#include "../../core/types_eig.h"
#include "../../data/field.h"
#include "../../data/region.h"

#include <cmath>
#include <memory>
#include <string>

namespace fem::bc {

/**
 * @brief Applies inertia forces associated with a prescribed rigid-body motion.
 *
 * Let `c` be the reference center, `a0` its translational acceleration, `omega`
 * the angular velocity and `alpha` the angular acceleration. For a material
 * point at global position `x`, with
 *
 *     r = x - c,
 *
 * the rigid-body acceleration represented by this load is
 *
 *     a(x) = a0 + alpha x r + omega x (omega x r).
 *
 * The equivalent distributed inertia contribution is
 *
 *     f_e = -integral_Omega_e rho N^T a(x) dOmega.
 *
 * A concentrated point mass `m` receives `-m a(x)`. If diagonal rotary inertia
 * `J` is present, the nodal moment additionally contains
 *
 *     M = -(J alpha + omega x (J omega)).
 *
 * The optional amplitude scales the complete force and moment contribution.
 */
struct InertialLoad : Condition {
    // Types
    using Ptr = std::shared_ptr<InertialLoad>;

    // Target rigid-body kinematics expressed in the global coordinate system.
    // These quantities determine the equivalent inertia forces and moments.
    Vec3 center_     = Vec3::Zero();
    Vec3 center_acc_ = Vec3::Zero();
    Vec3 omega_      = Vec3::Zero();
    Vec3 alpha_      = Vec3::Zero();

    // Optional initial rigid-body kinematics for step transitions. The center
    // is a geometric reference rather than a force magnitude. A linear ramp
    // of equivalent inertia forces cannot be implemented by simply ramping
    // omega: the centripetal and gyroscopic terms depend quadratically on it.
    // apply() interpolates complete inertia forces and moments derived from
    // the start and target states, rather than interpolating omega itself.
    Vec3 center_acc_start_ = Vec3::Constant(NAN);
    Vec3 omega_start_      = Vec3::Constant(NAN);
    Vec3 alpha_start_      = Vec3::Constant(NAN);

    // Scales the assembled initial inertia contribution, not its kinematics.
    // This is needed when an amplitude-driven load is retired: omega terms
    // enter quadratically, so scaling omega itself would be incorrect.
    Precision start_scale_ = Precision(1);

    // Structural elements whose distributed or compiled point mass contributes
    model::ElementRegion::Ptr region_ = nullptr;

    // Include auxiliary PointElements created after compilation by native
    // POINTMASS definitions. These objects do not belong to the dense ELSET
    // namespace and therefore require a separate traversal.
    bool consider_point_masses_ = false;

    // Construction
    InertialLoad() = default;
    ~InertialLoad() override = default;

    // Assemble the equivalent nodal inertia forces and moments associated
    // with the prescribed rigid-body acceleration field into the global RHS.
    //
    // Distributed mass contributes -integral(rho N^T a dOmega). Compiled
    // PointElements contribute concentrated translational forces and, where
    // rotary inertia is defined, the corresponding Euler/gyroscopic moments.
    // Auxiliary point masses are included when consider_point_masses_ is true.
    //
    // Without an amplitude, start and target inertia contributions are
    // interpolated using step_progress. The complete contributions are blended,
    // rather than angular velocities, because the centripetal and gyroscopic
    // terms are quadratic in omega. An assigned amplitude scales the target
    // contribution at time; ignore_amplitude assembles the nominal target.
    //
    // Only rhs is modified; equations, system_dof_ids and matrix are unchanged.
    void apply(
        model::ModelData&      model_data,
        model::Field&          rhs,
        constraint::Equations& equations,
        const SystemDofIds&    system_dof_ids,
        TripletList&           matrix,
        Precision              time,
        bool                   ignore_amplitude = false,
        Precision              step_progress   = Precision(1)
    ) override;

    // Diagnostics
    std::string str() const override;
};

} // namespace fem::bc
