/**
 * @file element_structural.h
 * @brief Declares the abstract base class for structural FEM elements.
 *
 * Structural elements extend `ElementInterface` with one state-based mechanical
 * evaluation used by linear, prestressed and nonlinear analyses. Independent
 * output pointers request the complete tangent, perturbation geometric stiffness
 * and/or internal force without forcing unrelated work. Mass and structural result recovery
 * remain separate while formulation-specific stress,
 * strain and constitutive integration remain responsibilities of the derived
 * element classes.
 *
 * The nonlinear interface is expressed in terms of nodal displacement and nodal
 * internal force. Stress and stress-resultant quantities required during an
 * element evaluation are temporary formulation data and do not form part of the
 * solver-facing interface.
 *
 * @see src/model/beam/beam.h
 *
 * @author Finn Eggers
 * @date 01.09.2026
 */

#pragma once

#include "element.h"
#include <functional>

namespace fem {
namespace model {

/**
 * @struct StructuralElement
 * @brief Common mechanical interface implemented by all structural elements.
 *
 * A structural element provides one mechanical state evaluation for the global
 * structural analyses. The caller independently requests the complete tangent,
 * the perturbation geometric stiffness and the internal force through nullable
 * output pointers. Target displacement and temperature define the requested
 * state (u,T), while base displacement and temperature define the state
 * (u0,T0) about which the displacement response is linearized. Null base fields
 * select zero displacement and the material stress-free temperature.
 *
 * The complete tangent is evaluated at (u0,T0). Internal force at a different
 * requested state is continued as
 *
 *     f_int(u,T) ~= f_int(u0,T) + K(u0,T0) (u-u0).
 *
 * The separate geometric output represents the stiffness generated by the
 * corresponding stress increment relative to the base state.
 *
 * Constitutive history follows a strict ownership rule. State-neutral evaluations
 * read committed material history without modifying the persistent trial state.
 * Only calls with `update_state=true` may write trial history. Promotion of trial
 * state to committed state belongs to the nonlinear increment controller, not to
 * an element.
 *
 * Stress, strain, constitutive tangents and stress resultants used while building
 * element operators are local intermediate quantities. Derived formulations may
 * keep them in local fixed-size storage or other formulation-local evaluation
 * data, but they are not exchanged with the global solver as scratch fields.
 * Result recovery remains available separately through `compute_stress_strain()`
 * and the formulation-specific recovery callbacks below.
 */
struct StructuralElement : ElementInterface {
    explicit StructuralElement(ID elem_id)
        : ElementInterface(elem_id) {}

    ~StructuralElement() override = default;

    // IMPORTANT: STRUCTURAL ELEMENT CONTRACT BELOW
    //
    // Evaluates the mechanical response of the element between a base state
    // (u0, T0) and a requested target state (u, T).
    //
    // target_displacement and target_temperature define the state for which the
    // element response is requested. base_displacement and base_temperature
    // define the state about which the mechanical response is linearized.
    //
    // A null base_displacement denotes u0 = 0. A null base_temperature denotes
    // the material stress-free reference temperature.
    //
    // The displacement increment relative to the base state is
    //
    //     du = u - u0.
    //
    // The complete tangent is evaluated at the base state:
    //
    //     K_T = d f_int / d u |_(u0,T0).
    //
    // A temperature change from the base temperature T0 to the target
    // temperature T is represented by the finite thermal force offset
    //
    //     df_T = f_int(u0,T) - f_int(u0,T0).
    //
    // The displacement dependence is then continued linearly from the base
    // displacement u0:
    //
    //     f_int(u,T)
    //       ~= f_int(u0,T0)
    //        + df_T
    //        + K_T(u0,T0) (u-u0).
    //
    // Equivalently,
    //
    //     f_int(u,T) ~= f_int(u0,T) + K_T(u0,T0) (u-u0).
    //
    // This separation is intentional. Temperature changes are evaluated as a
    // finite force offset at the fixed base geometry u0, while only the
    // displacement dependence is linearized about the base state.
    //
    // When target and base states are identical, i.e. (u,T) = (u0,T0), both
    // the thermal offset and displacement increment vanish and the evaluation
    // reduces to the exact element response
    //
    //     f_int(u0,T0).
    //
    // This is the normal usage during nonlinear Newton iterations, where the
    // current trial state is evaluated directly rather than by continuation
    // from a different state.
    //
    // tangent receives the complete tangent stiffness evaluated at (u0,T0).
    // This includes both material and geometric contributions that already
    // exist in the base state.
    //
    // geometric_tangent receives only the additional geometric-stiffness
    // contribution generated by the stress change between the base and target
    // states. Geometric stiffness already present at (u0,T0) is part of tangent
    // and is therefore not repeated.
    //
    // Any of tangent, geometric_tangent, or internal_force may be nullptr. The
    // corresponding quantity is then not evaluated or assembled, allowing the
    // caller to request only the response components it requires.
    //
    // update_state controls whether persistent constitutive trial history may be
    // written during the evaluation. State-neutral stiffness, perturbation and
    // result-recovery evaluations normally use false. Nonlinear evaluations may
    // use true when the constitutive trial state associated with the evaluated
    // mechanical state has to be stored.
    virtual MapMatrix evaluate(
        Precision*   tangent,
        Precision*   geometric_tangent,
        NodeData*    internal_force,
        const Field* target_displacement,
        const Field* target_temperature,
        const Field* base_displacement,
        const Field* base_temperature,
        bool         update_state
    ) = 0;

    // Inertial operator and formulation classification
    virtual Precision volume() = 0;
    virtual MapMatrix mass(Precision* buffer) = 0;
    virtual bool      is_shell() const { return false; }
    virtual bool      is_solid() const { return false; }

    // Natural-coordinate locations used by generic structural result recovery
    virtual RowMatrix stress_strain_nodal_rst() { return RowMatrix(0, 3); }
    virtual RowMatrix stress_strain_ip_rst() { return RowMatrix(0, 3); }

    // Some elements precompute step-local data and free it after the load case.
    virtual void step_begin() {}
    virtual void step_end()   {}

    // Field functors for volume/surface integrations (aliased to central types)
    using ScalarField = ::fem::ScalarField;
    using VecField    = ::fem::VecField;
    using TenField    = ::fem::TenField;

    // Integrate fields over the element measure (volume for solids/beams/trusses, area*thickness for shells)
    // Optionally scale by material density (per element).
    virtual Precision integrate_scalar_field(bool               scale_by_density,
                                             const ScalarField& field) = 0;
    virtual Vec3      integrate_vector_field(bool            scale_by_density,
                                             const VecField& field) = 0;
    virtual void      integrate_vector_field(Field&          node_loads,
                                             bool            scale_by_density,
                                             const VecField& field) = 0;
    virtual Mat3      integrate_tensor_field(bool            scale_by_density,
                                             const TenField& field) = 0;


    // Recovers physical stress and strain for this element at the requested
    // element-nodal recovery locations.
    //
    // target_displacement and target_temperature define the requested state
    // (u,T). base_displacement and base_temperature define the base state
    // (u0,T0) used for the same first-order continuation convention as evaluate().
    //
    // A null base_displacement denotes u0 = 0. A null base_temperature denotes
    // the material stress-free reference temperature.
    //
    // A temperature change from T0 to T is evaluated as a finite constitutive
    // change at the fixed base geometry u0, while the displacement dependence
    // from u0 to u is linearized about the base state.
    //
    // When target and base states are identical, i.e. (u,T) = (u0,T0), recovery
    // evaluates the exact stress and strain of that state.
    //
    // rst contains the natural coordinates at which element-nodal results are
    // requested. For ordinary nodal recovery these are the natural coordinates
    // of the element nodes. Shell recovery may additionally modify the
    // through-thickness coordinate to request top- or bottom-surface values.
    //
    // strain and stress, when non-null, must use the ELEMENT_NODAL domain.
    // Implementations write into the element's disjoint row range beginning at
    // elem_nodal_offset. The model-level recovery subsequently projects or
    // averages these element-local values onto global nodes.
    //
    // The operation is state-neutral. It may read committed constitutive history
    // but must not modify persistent material state.
    virtual void compute_stress_strain(
        Field*           strain,
        Field*           stress,
        const Field&     target_displacement,
        const Field*     target_temperature,
        const RowMatrix& rst,
        const Field*     base_displacement,
        const Field*     base_temperature
    ) = 0;

    // Recovers accumulated equivalent plastic strain from committed material
    // history into this element's disjoint ELEMENT_NODAL row range.
    //
    // Implementations use elem_nodal_offset to address their own rows.
    // Unsupported formulations return false and do not participate in the
    // subsequent model-wide nodal averaging.
    virtual bool compute_peeq(Field& peeq) {
        (void) peeq;
        return false;
    }

    // Computes the scalar compliance contribution of this element and writes it
    // into the ELEMENT-domain row addressed by elem_id.
    //
    // The displacement field defines the global structural state from which the
    // element contribution is evaluated.
    virtual void compute_compliance(Field& displacement, Field& result) {
        (void) displacement;
        (void) result;
    }

    // Computes the compliance derivatives with respect to the element material
    // orientation and writes them into the ELEMENT-domain row addressed by
    // elem_id.
    //
    // Unsupported formulations leave the initialized result row unchanged.
    virtual void compute_compliance_angle_derivative(Field& displacement, Field& result) {
        (void) displacement;
        (void) result;
    }

    // Recovers scalar shear flow at the element nodes into this element's
    // disjoint ELEMENT_NODAL row range.
    //
    // Implementations use elem_nodal_offset to address their own rows.
    // Unsupported formulations return false.
    virtual bool compute_shear_flow(Field& shear_flow, const Field& displacement) {
        (void) shear_flow;
        (void) displacement;
        return false;
    }

    // Recovers beam or line-element section forces at the element nodes into
    // this element's disjoint ELEMENT_NODAL row range.
    //
    // target_* defines the requested mechanical state (u,T), while base_*
    // defines the state (u0,T0) about which the response is linearized.
    // Null base fields denote zero displacement and the material stress-free
    // reference temperature.
    //
    // Implementations use elem_nodal_offset to address their own rows.
    // Unsupported formulations return false.
    virtual bool compute_beam_section_forces(
        Field&       section_forces,
        const Field& target_displacement,
        const Field* target_temperature,
        const Field* base_displacement = nullptr,
        const Field* base_temperature = nullptr
    ) {
        (void) section_forces;
        (void) target_displacement;
        (void) target_temperature;
        (void) base_displacement;
        (void) base_temperature;
        return false;
    }

    // Recovers shell membrane forces, bending moments and transverse shear
    // resultants and accumulates them directly into NODE-domain fields.
    //
    // Neighboring shell elements may contribute to the same global node.
    // section_forces therefore stores accumulated nodal contributions and
    // contribution_count records the corresponding number of contributions.
    // The model-level recovery subsequently reduces and averages these values.
    //
    // target_* defines the requested mechanical state (u,T), while base_*
    // defines the state (u0,T0) about which the response is linearized.
    // Null base fields denote zero displacement and the material stress-free
    // reference temperature.
    //
    // Unsupported formulations return false.
    virtual bool compute_shell_section_forces(
        Field&       section_forces,
        Field&       contribution_count,
        const Field& target_displacement,
        const Field* target_temperature,
        const Field* base_displacement = nullptr,
        const Field* base_temperature = nullptr
    ) {
        (void) section_forces;
        (void) contribution_count;
        (void) target_displacement;
        (void) target_temperature;
        (void) base_displacement;
        (void) base_temperature;
        return false;
    }
};
} // namespace model
} // namespace fem
