/**
 * @file element_structural.h
 * @brief Declares the abstract base class for structural FEM elements.
 *
 * Structural elements extend `ElementInterface` with one state-based mechanical
 * evaluation used by linear, prestressed and nonlinear analyses. Independent
 * output pointers request the complete tangent, perturbation geometric stiffness
 * and/or internal force without forcing unrelated work. Mass and structural result recovery
 * remain separate while formulation-specific stress,
 * strain and constitutive integration remain responsibilities of the derived
 * element classes.
 *
 * The nonlinear interface is expressed in terms of nodal displacement and nodal
 * internal force. Stress and stress-resultant quantities required during an
 * element evaluation are temporary formulation data and do not form part of the
 * solver-facing interface.
 *
 * @see src/model/beam/beam.h
 *
 * @author Finn Eggers
 * @date 01.09.2026
 */

#pragma once

#include "element.h"
#include <functional>

namespace fem {
namespace model {

/**
 * @struct StructuralElement
 * @brief Common mechanical interface implemented by all structural elements.
 *
 * A structural element provides one mechanical state evaluation for the global
 * structural analyses. The caller independently requests the complete tangent,
 * the perturbation geometric stiffness and the internal force through nullable
 * output pointers. Target displacement and temperature define the requested
 * state (u,T), while base displacement and temperature define the state
 * (u0,T0) about which the displacement response is linearized. Null base fields
 * select zero displacement and the material stress-free temperature.
 *
 * The complete tangent is evaluated at (u0,T0). Internal force at a different
 * requested state is continued as
 *
 *     f_int(u,T) ~= f_int(u0,T) + K(u0,T0) (u-u0).
 *
 * The separate geometric output represents the stiffness generated by the
 * corresponding stress increment relative to the base state.
 *
 * Constitutive history follows a strict ownership rule. State-neutral evaluations
 * read committed material history without modifying the persistent trial state.
 * Only calls with `update_state=true` may write trial history. Promotion of trial
 * state to committed state belongs to the nonlinear increment controller, not to
 * an element.
 *
 * Stress, strain, constitutive tangents and stress resultants used while building
 * element operators are local intermediate quantities. Derived formulations may
 * keep them in local fixed-size storage or other formulation-local evaluation
 * data, but they are not exchanged with the global solver as scratch fields.
 * Result recovery remains available separately through `compute_stress_strain()`
 * and the formulation-specific recovery callbacks below.
 */
struct StructuralElement : ElementInterface {
    explicit StructuralElement(ID elem_id)
        : ElementInterface(elem_id) {}

    ~StructuralElement() override = default;

    // Mechanical state evaluation. target_* defines the requested state (u,T)
    // and base_* defines the linearization state (u0,T0). Null base fields denote
    // zero displacement and the material stress-free temperature. The complete
    // tangent is evaluated at (u0,T0), while the force anchor uses (u0,T).
    // Null output pointers deliberately skip work that the caller does not need.
    // Persistent constitutive history is written only when update_state is true.
    virtual MapMatrix evaluate(
        Precision*   tangent,
        Precision*   geometric_tangent,
        NodeData*    internal_force,
        const Field* target_displacement,
        const Field* target_temperature,
        const Field* base_displacement,
        const Field* base_temperature,
        bool         update_state
    ) = 0;

    // Inertial operator and formulation classification
    virtual Precision volume() = 0;
    virtual MapMatrix mass(Precision* buffer) = 0;
    virtual bool      is_shell() const { return false; }
    virtual bool      is_solid() const { return false; }

    // Natural-coordinate locations used by generic structural result recovery
    virtual RowMatrix stress_strain_nodal_rst() { return RowMatrix(0, 3); }
    virtual RowMatrix stress_strain_ip_rst() { return RowMatrix(0, 3); }

    // Some elements precompute step-local data and free it after the load case.
    virtual void step_begin() {}
    virtual void step_end()   {}

    // Field functors for volume/surface integrations (aliased to central types)
    using ScalarField = ::fem::ScalarField;
    using VecField    = ::fem::VecField;
    using TenField    = ::fem::TenField;

    // Integrate fields over the element measure (volume for solids/beams/trusses, area*thickness for shells)
    // Optionally scale by material density (per element).
    virtual Precision integrate_scalar_field(bool               scale_by_density,
                                             const ScalarField& field) = 0;
    virtual Vec3      integrate_vector_field(bool            scale_by_density,
                                             const VecField& field) = 0;
    virtual void      integrate_vector_field(Field&          node_loads,
                                             bool            scale_by_density,
                                             const VecField& field) = 0;
    virtual Mat3      integrate_tensor_field(bool            scale_by_density,
                                             const TenField& field) = 0;


    // State-neutral recovery between target state (u,T) and base state (u0,T0).
    // Null base fields denote zero displacement and the material stress-free
    // temperature. Recovery writes result fields independently of temporary
    // stresses used during operator assembly.
    virtual void compute_stress_strain(
        Field*           strain,
        Field*           stress,
        const Field&     target_displacement,
        const Field*     target_temperature,
        const RowMatrix& rst,
        int              offset,
        const Field*     base_displacement,
        const Field*     base_temperature
    ) = 0;

    // Recover accumulated equivalent plastic strain from committed material
    // history into this element's disjoint ELEMENT_NODAL row range. Unsupported
    // formulations return false and do not participate in model-wide averaging.
    virtual bool compute_peeq(Field& peeq, int offset) {
        (void) peeq;
        (void) offset;
        return false;
    }
    virtual void compute_compliance(Field& displacement, Field& result) {
        (void) displacement;
        (void) result;
    }
    virtual void compute_compliance_angle_derivative(Field& displacement, Field& result) {
        (void) displacement;
        (void) result;
    }
    virtual bool compute_shear_flow(Field& shear_flow, const Field& displacement, int offset) {
        (void) shear_flow;
        (void) displacement;
        (void) offset;
        return false;
    }
    virtual bool compute_beam_section_forces(
        Field&       section_forces,
        const Field& target_displacement,
        const Field* target_temperature,
        int          offset,
        const Field* base_displacement = nullptr,
        const Field* base_temperature = nullptr
    ) {
        (void) section_forces;
        (void) target_displacement;
        (void) target_temperature;
        (void) offset;
        (void) base_displacement;
        (void) base_temperature;
        return false;
    }
    virtual bool compute_shell_section_forces(Field&       section_forces,
                                              Field&       contribution_count,
                                              const Field& target_displacement,
                                              const Field* target_temperature,
                                              const Field* base_displacement = nullptr,
                                              const Field* base_temperature = nullptr) {
        (void) section_forces;
        (void) contribution_count;
        (void) target_displacement;
        (void) target_temperature;
        (void) base_displacement;
        (void) base_temperature;
        return false;
    }
};
} // namespace model
} // namespace fem
