"""FEMaster input deck writer for the neutral Python model."""

from __future__ import annotations

from pathlib import Path

from femaster_api.export.femaster_format import join_blocks
from femaster_api.export.serializers import (
    write_boundaries,
    write_constraints,
    write_elements,
    write_features,
    write_fields,
    write_loads,
    write_materials,
    write_nodes,
    write_orientations,
    write_sections,
    write_sets,
    write_steps,
    write_surfaces,
)
from femaster_api.model.model import Model


class FEMasterWriter:
    """Render a neutral model into FEMaster's text input-deck DSL."""

    def __init__(self, model: Model, *, include_header: bool = True) -> None:
        self.model = model
        self.include_header = include_header

    def write(self, path: str | Path) -> None:
        Path(path).write_text(self.render(), encoding="utf-8")

    def render(self) -> str:
        blocks = [
            self._heading(),
            write_nodes(self.model.nodes),
            write_elements(self.model.elements),
            write_sets(self.model.sets),
            write_surfaces(self.model.surfaces),
            write_orientations(self.model.orientations),
            write_materials(self.model.materials),
            write_sections(self.model.sections),
            write_fields(self.model.fields),
            write_features(self.model.features),
            write_boundaries(self.model.support_collectors),
            write_loads(self.model.loads, self.model.load_collectors),
            write_constraints(self.model.constraints),
            write_steps(self.model.steps),
        ]
        return join_blocks(blocks)

    def _heading(self) -> str:
        if not self.include_header:
            return ""
        return "\n".join(
            (
                f"** FEMaster deck generated by femaster_api for model: {self.model.name}",
                "** Model objects and FEMaster deck syntax are intentionally separated.",
            )
        )
