/**
 * @file load_inertial.h
 * @brief Declares equivalent loads for prescribed rigid-body acceleration.
 *
 * `InertialLoad` evaluates the acceleration field generated by translation,
 * angular acceleration and angular velocity about a reference point. Structural
 * elements integrate the negative acceleration with their distributed density,
 * while point elements contribute concentrated translational mass and rotary
 * inertia through their `PointMassSection`.
 *
 * Regular compiled point elements participate when they belong to the selected
 * element region. Auxiliary point elements created by point-mass features may be
 * included separately through `consider_point_masses_`, preserving the existing
 * distinction between compiled ELSET topology and post-compile point masses.
 *
 * @see InertialLoad
 * @see StructuralNeumann
 * @see model::PointElement
 * @see PointMassSection
 * @see load_inertial.cpp
 *
 * @author Finn Eggers
 * @date 25.08.2026
 */

#pragma once

#include "neumann.h"
#include "../../data/region.h"

namespace fem::bc {

/**
 * @brief Represents a translational and rotational rigid-body inertia field.
 *
 * At physical position `x`, with `r = x - center_`, the prescribed rigid-body
 * acceleration is
 *
 *     center_acc_ + alpha_ x r + omega_ x (omega_ x r).
 *
 * Equivalent inertia force uses the opposite sign. Distributed structural
 * elements provide their own density and interpolation. Point-mass sections add
 * concentrated translational force and, when rotational components are present
 * in the target field, Euler and gyroscopic rotary-inertia moments.
 */
struct InertialLoad : StructuralNeumann {
    // Shared ownership type for direct references to inertial loads.
    using Ptr = std::shared_ptr<InertialLoad>;

    // Global reference point from which the rotational radius vector is measured.
    Vec3 center_ = {0, 0, 0};

    // Prescribed translational acceleration of the reference point.
    Vec3 center_acc_ = {0, 0, 0};

    // Prescribed angular velocity used for centripetal acceleration and the
    // gyroscopic point-mass moment.
    Vec3 omega_ = {0, 0, 0};

    // Prescribed angular acceleration used for tangential acceleration and
    // concentrated rotary-inertia moments.
    Vec3 alpha_ = {0, 0, 0};

    // Element region whose structural elements integrate the distributed mass
    // contribution. Compiled point elements in this region are handled directly.
    SPtr<model::ElementRegion> region_ = nullptr;

    // Include auxiliary post-compile point-mass elements as additional
    // concentrated inertia terms when true.
    bool consider_point_masses_ = false;

    // Integrate the negative rigid-body acceleration over selected structural
    // elements using density scaling and optionally add translational and rotary
    // contributions of auxiliary point-mass features.
    void apply(model::ModelData& model_data,
               model::Field&     rhs,
               Precision         time,
               bool              ignore_amplitude = false) override;

    // Return the target region, reference point, translational acceleration,
    // angular kinematics and point-mass option in one diagnostic string.
    std::string str() const override;
};

} // namespace fem::bc
