/**
 * @file load_inertial.h
 * @brief Declares equivalent loads for prescribed rigid-body acceleration.
 *
 * `InertialLoad` evaluates the acceleration field generated by translation,
 * angular acceleration and angular velocity about a reference point. Structural
 * elements integrate the negative acceleration with distributed density and
 * optional point-mass handling adds concentrated inertia contributions.
 *
 * @see InertialLoad
 * @see Neumann
 * @see load_inertial.cpp
 * @author Finn Eggers
 * @date 06.03.2025
 */

#pragma once

#include "neumann.h"

#include "../../data/region.h"

namespace fem::bc {

/**
 * @brief Represents a translational and rotational rigid-body inertia field.
 */
struct InertialLoad : Neumann {
    using Ptr = std::shared_ptr<InertialLoad>;

    // Rigid-body kinematic definition in global coordinates.
    Vec3 center_     = {0, 0, 0};
    Vec3 center_acc_ = {0, 0, 0};
    Vec3 omega_      = {0, 0, 0};
    Vec3 alpha_      = {0, 0, 0};

    // Structural elements contributing distributed inertia.
    SPtr<model::ElementRegion> region_ = nullptr;

    // Include auxiliary point-mass elements when true.
    bool consider_point_masses_ = false;

    InertialLoad() = default;
    ~InertialLoad() override = default;

    void apply(model::ModelData& model_data, model::Field& bc, Precision time, bool ignore_amplitude = false) override;
    std::string str() const override;
};

} // namespace fem::bc
