/**
 * @file constraint_build_report.h
 * @brief Declares diagnostic information produced while constructing a constraint representation.
 *
 * A `ConstraintBuildReport` summarizes the dimensions, numerical rank,
 * redundancy, consistency and affine right-hand side of an assembled constraint
 * system. It is returned together with the transformation data generated by
 * elimination and null-space construction and allows callers to inspect whether
 * the original system
 *
 *     C u = d
 *
 * could be represented consistently.
 *
 * The report does not own the constraint matrix or transformation itself. It
 * only stores scalar metadata and numerical diagnostics determined during the
 * selected construction procedure.
 *
 * @see ConstraintSystem
 * @see ConstraintMap
 * @see build_elimination
 * @see build_null_space
 *
 * @author Finn Eggers
 */

#pragma once

#include "../../core/types_eig.h"

namespace fem {
namespace constraint {

/**
 * @brief Summarizes the result of constructing a constraint representation.
 *
 * The report describes the original assembled constraint system and the
 * numerical properties detected while converting it into a reduced or
 * augmented representation. Depending on the selected enforcement method, the
 * rank may be determined explicitly or remain unknown.
 *
 * A feasible report indicates that the computed particular solution satisfies
 * the assembled equations within the tolerance used by the corresponding
 * construction algorithm. Redundant rows are equations that do not introduce
 * an additional independent constraint.
 */
struct ConstraintBuildReport {
    // Number of assembled constraint equations. This corresponds to the number
    // of rows in the global constraint matrix C.
    Index equations{};

    // Number of active full-system degrees of freedom addressed by the
    // constraint matrix. This corresponds to the number of columns in C.
    Index dofs{};

    // Numerically determined rank of the assembled constraint matrix. For
    // reduced formulations, this is also the number of dependent directions
    // removed from the full system.
    Index rank{};

    // Number of assembled equations that were identified as linearly dependent
    // and therefore did not increase the numerical rank of the system.
    Index redundant_rows{};

    // Euclidean norm of the assembled constraint right-hand side d. This value
    // provides the scale used by relative feasibility checks for inhomogeneous
    // constraint systems.
    Precision rhs_norm{Precision(0)};

    // Norm of the residual remaining after inserting the computed particular
    // solution into the original equations:
    //
    //     ||C u_p - d||.
    //
    // A small value indicates that the affine part of the generated
    // transformation satisfies the assembled constraints.
    Precision residual_norm{Precision(0)};

    // True when the assembled right-hand side d is identically zero and the
    // constraint system therefore defines a homogeneous subspace C u = 0.
    bool homogeneous{true};

    // True when the constraint equations are mutually consistent within the
    // numerical feasibility tolerance used by the construction algorithm.
    bool feasible{true};

    // True when rank contains an explicitly computed numerical rank. Methods
    // that do not perform a rank-revealing decomposition may leave this false.
    bool rank_known{true};
};

} // namespace constraint
} // namespace fem