/**
 * @file truss_evaluate.cpp
 * @brief Implements the state-based mechanical evaluation of the T3 truss.
 *
 * The formulation uses one common interpretation of the two displacement
 * arguments:
 *
 *     u0 = linearization state,
 *     u  = requested state,
 *     Delta u = u - u0.
 *
 * A null linearization denotes u0 = 0. The complete tangent is evaluated at u0,
 * while the separately requested geometric stiffness is generated only by the
 * linearized stress increment caused by Delta u. This is the same mechanical
 * contract used by the continuum solid elements.
 *
 * @see T3
 *
 * @author Finn Eggers
 * @date 04.10.2026
 */

#include "truss.h"

namespace fem {
namespace model {

/**
 * Evaluates the truss response about a selected linearization state u0.
 *
 * The finite truss kinematics are defined by the reference axis
 *
 *     R0 = X2 - X1,             L0 = ||R0||
 *
 * and the axis at the linearization state
 *
 *     r0 = R0 + u0,2 - u0,1,   l0 = ||r0||,
 *     lambda0 = l0 / L0,       n0 = r0 / l0.
 *
 * The Green-Lagrange axial strain is
 *
 *     E0 = 1/2 (lambda0^2 - 1),
 *
 * with work-conjugate second Piola-Kirchhoff stress S0. The element internal
 * force at the base state is
 *
 *     f_int(u0) = A0 lambda0 S0 [-n0, +n0]^T.
 *
 * Linearizing this force gives the complete Total-Lagrangian tangent
 *
 *     K_T(u0) = K_M(u0) + K_G(S0),
 *
 * where one 3x3 nodal block is
 *
 *     K_M,block = A0 C0 lambda0^2 / L0 (n0 tensor n0),
 *     K_G,block = A0 S0 / L0 I.
 *
 * When u differs from u0, force is continued affinely:
 *
 *     f_int(u) ~= f_int(u0) + K_T(u0) (u - u0).
 *
 * The separately requested geometric operator does not repeat K_G(S0). Instead
 * the displacement perturbation produces
 *
 *     Delta E = lambda0 / L0 n0 . (Delta u2 - Delta u1),
 *     Delta S = C0 Delta E,
 *
 * and the returned operator is K_G(Delta S).
 *
 * At u0 = 0, lambda0 = 1 and n0 equals the reference direction. The same
 * equations therefore reduce to the ordinary infinitesimal truss formulation.
 *
 * @param tangent_buffer Optional storage for the complete tangent K_T(u0).
 * @param geometric_tangent_buffer Optional storage for K_G(Delta S).
 * @param internal_force Optional global nodal force accumulator.
 * @param displacement Requested displacement state u.
 * @param linearization Optional base displacement state u0; nullptr denotes zero.
 * @param thermal_free_strain Unused by the current truss formulation.
 * @param update_state Allow an exact constitutive evaluation at u0 to write trial history.
 * @return Map onto the first requested matrix output, or an empty map for force-only evaluation.
 */
MapMatrix T3::evaluate(
    Precision*   tangent_buffer,
    Precision*   geometric_tangent_buffer,
    NodeData*    internal_force,
    const Field* displacement,
    const Field* linearization,
    const Field* thermal_free_strain,
    bool         update_state
) {
    (void) thermal_free_strain;


    // -----------------------------------------------------------------------------
    // requested outputs
    // -----------------------------------------------------------------------------

    // Requested element outputs:
    // - complete tangent stiffness at the linearization state u0
    // - geometric stiffness generated by the stress increment from u0 to u
    // - internal force at the requested displacement state u
    const bool with_tangent   = tangent_buffer           != nullptr;
    const bool with_geometric = geometric_tangent_buffer != nullptr;
    const bool with_force     = internal_force           != nullptr;


    // -----------------------------------------------------------------------------
    // reference geometry and evaluation state
    // -----------------------------------------------------------------------------

    // A0 and L0 define the one-dimensional reference measure A0 dX. Both the
    // infinitesimal and Total-Lagrangian formulations are expressed with respect
    // to this undeformed configuration.
    const Precision A0 = get_section()->area_;
    const Precision L0 = length_reference();

    logging::error(with_tangent || with_geometric || with_force,
        "T3: evaluation requires at least one requested output");
    logging::error(!with_force || displacement != nullptr,
        "T3: internal force evaluation requires displacement");
    logging::error(!update_state || (linearization != nullptr && displacement == linearization),
        "T3: material state requires an exact evaluation at the linearization state");
    logging::error(L0 > Precision(0),
        "T3: zero reference length for element ", this->elem_id);

    // Collect u0 and Delta u = u - u0 in local nodal ordering. A null
    // linearization leaves u0 at zero, so the same path also represents
    // reference-state linearization.
    StaticMatrix<N, 3> disp_linear_base = StaticMatrix<N, 3>::Zero();
    StaticMatrix<N, 3> disp_delta       = StaticMatrix<N, 3>::Zero();

    if (linearization) {
        disp_linear_base.row(0) = linearization->row_vec3(static_cast<Index>(node_ids[0])).transpose();
        disp_linear_base.row(1) = linearization->row_vec3(static_cast<Index>(node_ids[1])).transpose();
    }

    if (displacement) {
        disp_delta.row(0) = displacement->row_vec3(static_cast<Index>(node_ids[0])).transpose() - disp_linear_base.row(0);
        disp_delta.row(1) = displacement->row_vec3(static_cast<Index>(node_ids[1])).transpose() - disp_linear_base.row(1);
    }

    // Only the relative nodal perturbation changes the one-dimensional axial
    // strain. A rigid translation therefore gives delta_axis = 0 exactly.
    const Vec3 delta_axis = (disp_delta.row(1) - disp_delta.row(0)).transpose();


    // -----------------------------------------------------------------------------
    // required internal quantities
    // -----------------------------------------------------------------------------

    // Force away from the base state uses the affine residual approximation
    //
    //     f_int(u) ~= f_int(u0) + K_T(u0) Delta u.
    //
    // Consequently the complete tangent may be needed even when the caller did
    // not request it as an output.
    const bool affine_force = with_force && displacement != linearization;
    const bool need_tangent = with_tangent || affine_force;

    // The material tangent C0 = dS/dE is required for the material stiffness and
    // for the perturbation stress Delta S used by the separate geometric matrix.
    const bool need_material = need_tangent || with_geometric;


    // -----------------------------------------------------------------------------
    // constitutive history
    // -----------------------------------------------------------------------------

    auto elasticity = get_elasticity();

    // T3 owns one constitutive material point. Every evaluation reads the
    // committed history. A writable target exists only when update_state is true;
    // validation above restricts that case to the exact physical state u = u0.
    const Index      state_row = this->mp_index(0);
    const Precision* old_state = &(*this->_model_data->material_state_old)(state_row, 0);
    Precision*       new_state = update_state ? &(*this->_model_data->material_state_new)(state_row, 0) : nullptr;


    // -----------------------------------------------------------------------------
    // kinematics and constitutive response at u0
    // -----------------------------------------------------------------------------

    // These scalar/vector quantities provide one common representation of the
    // base state for all later assembly. At u0 = 0 they take their reference
    // values lambda0 = 1 and n0 = N0.
    Vec3      direction_base   = direction_reference();
    Precision stretch_base     = Precision(1);
    Precision stress_base      = Precision(0);
    Precision material_tangent = Precision(0);

    if (linearization == nullptr) {
        // At the undeformed reference state the infinitesimal strain is exactly
        // zero. Cauchy stress and PK2 stress coincide because F = I.
        logging::error(elasticity->supports_axial_linearized(),
            "T3: material does not support linearized axial evaluation for element ",
            this->elem_id);

        AxialStressCauchy stress;
        elasticity->evaluate(
            AxialStrainLinearized(Precision(0)),
            old_state,
            new_state,
            stress,
            need_material ? &material_tangent : nullptr
        );

        stress_base = stress.value();

    } else {
        // Construct the base axis directly from the supplied linearization
        // displacement rather than from the model's current POSITION field:
        //
        //     x0,i = X_i + u0,i,
        //     r0   = x0,2 - x0,1.
        logging::error(elasticity->supports_axial_green_lagrange(),
            "T3: material does not support Green-Lagrange axial evaluation for element ",
            this->elem_id);

        const Vec3 X0        = node_position_reference(0);
        const Vec3 X1        = node_position_reference(1);
        const Vec3 x0        = X0 + disp_linear_base.row(0).transpose();
        const Vec3 x1        = X1 + disp_linear_base.row(1).transpose();
        const Vec3 axis_base = x1 - x0;

        const Precision length_base = axis_base.norm();
        logging::error(length_base > Precision(0),
            "T3: zero length at the linearization state for element ", this->elem_id);

        stretch_base   = length_base / L0;
        direction_base = axis_base / length_base;

        // For a two-node truss the Green-Lagrange strain is constant:
        //
        //     E0 = 1/2 (lambda0^2 - 1).
        const AxialStrainGreenLagrange strain =
            AxialStrainGreenLagrange::from_stretch(stretch_base);

        AxialStressPK2 stress;
        elasticity->evaluate(
            strain,
            old_state,
            new_state,
            stress,
            need_material ? &material_tangent : nullptr
        );

        stress_base = stress.value();
    }


    // -----------------------------------------------------------------------------
    // complete tangent stiffness at u0
    // -----------------------------------------------------------------------------

    StaticMatrix<N * 3, N * 3> tangent = StaticMatrix<N * 3, N * 3>::Zero();

    if (need_tangent) {
        // Differentiating
        //
        //     f2 = A0 lambda0 S0 n0 = A0/L0 S0 r0
        //
        // yields
        //
        //     df2 = A0/L0 [S0 I + C0 lambda0^2 (n0 tensor n0)] d(r0).
        //
        // The first term is the initial-stress/geometric contribution; the
        // second is the constitutive/material contribution.
        const Mat3 material_block  = (A0 * material_tangent * stretch_base * stretch_base / L0)
                                   * (direction_base * direction_base.transpose());
        const Mat3 geometric_block = (A0 * stress_base / L0) * Mat3::Identity();
        const Mat3 tangent_block   = material_block + geometric_block;

        // Node 1 and node 2 enter the relative axis with opposite signs:
        //
        //     d(r0) = du2 - du1.
        //
        // This gives the standard [ K -K; -K K ] truss block structure.
        tangent.block(0, 0, 3, 3) =  tangent_block;
        tangent.block(0, 3, 3, 3) = -tangent_block;
        tangent.block(3, 0, 3, 3) = -tangent_block;
        tangent.block(3, 3, 3, 3) =  tangent_block;
    }


    // -----------------------------------------------------------------------------
    // geometric stiffness generated by the perturbation from u0 to u
    // -----------------------------------------------------------------------------

    StaticMatrix<N * 3, N * 3> geometric = StaticMatrix<N * 3, N * 3>::Zero();

    if (with_geometric) {
        // The first variation of
        //
        //     E = 1/2 (r.r / L0^2 - 1)
        //
        // at r0 = lambda0 L0 n0 is
        //
        //     Delta E = r0 . Delta r / L0^2
        //             = lambda0 n0 . Delta r / L0.
        const Precision strain_increment = stretch_base * direction_base.dot(delta_axis) / L0;

        // Linearize the constitutive response at u0:
        //
        //     Delta S = C0 Delta E.
        //
        // Only Delta S enters this separately requested operator. S0 already
        // appears in the complete tangent assembled above.
        const Precision stress_increment = material_tangent * strain_increment;
        const Mat3 geometric_block       = (A0 * stress_increment / L0) * Mat3::Identity();

        geometric.block(0, 0, 3, 3) =  geometric_block;
        geometric.block(0, 3, 3, 3) = -geometric_block;
        geometric.block(3, 0, 3, 3) = -geometric_block;
        geometric.block(3, 3, 3, 3) =  geometric_block;
    }


    // -----------------------------------------------------------------------------
    // internal force
    // -----------------------------------------------------------------------------

    if (with_force) {
        StaticVector<N * 3> force = StaticVector<N * 3>::Zero();

        // The Total-Lagrangian nodal force follows directly from
        //
        //     delta W_int = A0 L0 S0 delta E,
        //
        // with
        //
        //     dE/du1 = -lambda0 n0 / L0,
        //     dE/du2 = +lambda0 n0 / L0.
        //
        // Therefore
        //
        //     f1 = -A0 lambda0 S0 n0,
        //     f2 = +A0 lambda0 S0 n0.
        const Vec3 axial_force = A0 * stretch_base * stress_base * direction_base;

        force.template segment<3>(0) = -axial_force;
        force.template segment<3>(3) =  axial_force;

        // Continue the residual from u0 to u only when the requested state is
        // different from the linearization state.
        if (affine_force) {
            StaticVector<N * 3> delta = StaticVector<N * 3>::Zero();
            delta.template segment<3>(0) = disp_delta.row(0).transpose();
            delta.template segment<3>(3) = disp_delta.row(1).transpose();

            force.noalias() += tangent * delta;
        }

        // Scatter the local six-component force into the global nodal field.
        const Index node0 = static_cast<Index>(node_ids[0]);
        const Index node1 = static_cast<Index>(node_ids[1]);

        for (Dim d = 0; d < 3; ++d) {
            (*internal_force)(node0, d) += force(d);
            (*internal_force)(node1, d) += force(3 + d);
        }
    }


    // -----------------------------------------------------------------------------
    // copy requested operators into caller-owned storage
    // -----------------------------------------------------------------------------

    if (with_tangent) {
        MapMatrix mapped(tangent_buffer, N * 3, N * 3);
        mapped = tangent;
    }

    if (with_geometric) {
        MapMatrix mapped(geometric_tangent_buffer, N * 3, N * 3);
        mapped = geometric;
    }

    return with_tangent   ? MapMatrix(tangent_buffer,           N * 3, N * 3)
         : with_geometric ? MapMatrix(geometric_tangent_buffer, N * 3, N * 3)
                          : MapMatrix(nullptr, 0, 0);
}

} // namespace model
} // namespace fem
