/**
 * @file truss_evaluate.cpp
 * @brief Implements the state-based mechanical evaluation of the T3 truss.
 *
 * Mechanical evaluation uses two explicit physical states:
 *
 *     target = (u, T),
 *     base   = (u0, T0).
 *
 * The complete tangent is evaluated at the base state. Temperature changes are
 * evaluated exactly at fixed base geometry, while displacement changes are
 * linearized about the base state:
 *
 *     f_int(u,T) ~= f_int(u0,T) + K(u0,T0) (u-u0).
 *
 * The separately requested geometric stiffness is generated by the stress
 * increment relative to the base state and therefore does not repeat the
 * geometric contribution already contained in the complete tangent.
 *
 * @see T3
 *
 * @author Finn Eggers
 * @date 04.10.2026
 */

#include "truss.h"

namespace fem {
namespace model {

/**
 * Evaluates the truss response about a selected linearization state u0.
 *
 * The reference axis is
 *
 *     R = X2 - X1,
 *     L0 = ||R||.
 *
 * The exact configuration at the linearization state is
 *
 *     r0 = (X2 + u0,2) - (X1 + u0,1),
 *     l0 = ||r0||,
 *     lambda0 = l0 / L0,
 *     n0 = r0 / l0.
 *
 * The Green-Lagrange axial strain at u0 is
 *
 *     E0 = 1/2 (lambda0^2 - 1).
 *
 * Thermal expansion contributes the free axial strain
 *
 *     E_th = alpha (T - T0),
 *
 * so the material response is evaluated from the mechanical strain
 *
 *     E_mech,0 = E0 - E_th.
 *
 * The work-conjugate second Piola-Kirchhoff stress is therefore
 *
 *     S0 = S(E_mech,0)
 *
 * with material tangent
 *
 *     C0 = dS/dE_mech | E_mech,0.
 *
 * The internal force at the linearization state follows from
 *
 *     f_int(u0) = A0 lambda0 S0 [-n0, +n0]^T.
 *
 * Linearizing this force gives the complete Total-Lagrangian tangent
 *
 *     K_T(u0) = K_M(u0) + K_G(S0),
 *
 * where one 3x3 nodal block is
 *
 *     K_M = A0 C0 lambda0^2 / L0 (n0 tensor n0),
 *
 *     K_G = A0 S0 / L0 I.
 *
 * For a requested state u different from u0,
 *
 *     Delta u = u - u0
 *
 * and
 *
 *     Delta r = Delta u2 - Delta u1.
 *
 * Linearization of the Green-Lagrange strain gives
 *
 *     Delta E = lambda0 / L0 n0 . Delta r.
 *
 * The temperature change T0 -> T is evaluated exactly at u0. The displacement
 * increment is then linearized with the tangent of the base state:
 *
 *     Delta S = S(u0,T) - S(u0,T0) + C0 Delta E.
 *
 * Internal force is continued according to
 *
 *     f_int(u,T) ~= f_int(u0,T) + K_T(u0,T0) Delta u.
 *
 * The separately requested geometric operator is generated only by Delta S:
 *
 *     K_G^Delta = K_G(Delta S).
 *
 * A null linearization simply gives u0 = 0. Consequently
 *
 *     r0 = R,
 *     lambda0 = 1,
 *     E0 = 0,
 *
 * without requiring a separate infinitesimal formulation. A thermal strain may
 * nevertheless produce a non-zero base stress S0 and therefore contributes to
 * both the reference internal force and the tangent at u0.
 */
MapMatrix T3::evaluate(
    Precision*   tangent_buffer,
    Precision*   geometric_tangent_buffer,
    NodeData*    internal_force,
    const Field* target_displacement,
    const Field* target_temperature,
    const Field* base_displacement,
    const Field* base_temperature,
    bool         update_state
) {
    // -----------------------------------------------------------------------------
    // requested outputs
    // -----------------------------------------------------------------------------

    // Requested element outputs:
    // - complete tangent stiffness K_T(u0)
    // - geometric stiffness generated by Delta S from u0 to u
    // - internal force at the requested state u
    const bool with_tangent   = tangent_buffer           != nullptr;
    const bool with_geometric = geometric_tangent_buffer != nullptr;
    const bool with_force     = internal_force           != nullptr;

    // -----------------------------------------------------------------------------
    // displacement states
    // -----------------------------------------------------------------------------

    // A null base displacement denotes u0 = 0. Store both nodal base
    // displacements explicitly so all following expressions use the same state
    // description.
    StaticMatrix<N, 3> disp_base = StaticMatrix<N, 3>::Zero();

    if (base_displacement) {
        disp_base.row(0) = base_displacement->row_vec3(static_cast<Index>(node_ids[0])).transpose();
        disp_base.row(1) = base_displacement->row_vec3(static_cast<Index>(node_ids[1])).transpose();
    }

    // -----------------------------------------------------------------------------
    // exact geometry at the linearization state u0
    // -----------------------------------------------------------------------------

    // Reference geometry:
    //
    //     R  = X2 - X1,
    //     L0 = ||R||.
    const Vec3 X1 = node_position_reference(0);
    const Vec3 X2 = node_position_reference(1);

    const Vec3      reference_axis = X2 - X1;
    const Precision L0             = reference_axis.norm();
    const Precision A0             = get_section()->area_;

    // Exact geometry at u0:
    //
    //     x0,1 = X1 + u0,1,
    //     x0,2 = X2 + u0,2,
    //
    //     r0 = x0,2 - x0,1.
    const Vec3 x01       = X1 + disp_base.row(0).transpose();
    const Vec3 x02       = X2 + disp_base.row(1).transpose();
    const Vec3 axis_base = x02 - x01;

    const Precision length_base = axis_base.norm();

    auto elasticity = get_elasticity();

    // -----------------------------------------------------------------------------
    // validation
    // -----------------------------------------------------------------------------

    logging::error(with_tangent || with_geometric || with_force,
        "T3: evaluation requires at least one requested output");
    logging::error(!with_force || target_displacement != nullptr,
        "T3: internal force evaluation requires displacement");
    logging::error(!update_state ||
        (base_displacement != nullptr && target_displacement == base_displacement &&
         target_temperature == base_temperature),
        "T3: material state requires an exact evaluation at the base state");
    logging::error(L0 > Precision(0),
        "T3: zero reference length for element ", this->elem_id);
    logging::error(length_base > Precision(0),
        "T3: zero length at the linearization state for element ", this->elem_id);

    // -----------------------------------------------------------------------------
    // displacement increment from u0 to u
    // -----------------------------------------------------------------------------

    // Gather
    //
    //     Delta u = u - u0.
    //
    // If no requested displacement is supplied, Delta u remains zero.
    StaticMatrix<N, 3> disp_delta = StaticMatrix<N, 3>::Zero();

    if (target_displacement) {
        disp_delta.row(0) = target_displacement->row_vec3(static_cast<Index>(node_ids[0])).transpose() - disp_base.row(0);
        disp_delta.row(1) = target_displacement->row_vec3(static_cast<Index>(node_ids[1])).transpose() - disp_base.row(1);
    }

    // Only relative nodal motion contributes to axial deformation:
    //
    //     Delta r = Delta u2 - Delta u1.
    //
    // A rigid translation therefore gives Delta r = 0.
    const Vec3 delta_axis = (disp_delta.row(1) - disp_delta.row(0)).transpose();

    // -----------------------------------------------------------------------------
    // required internal quantities
    // -----------------------------------------------------------------------------

    // Force away from the base state requires
    //
    //     f_int(u) ~= f_int(u0) + K_T(u0) Delta u.
    //
    // Therefore K_T may be required internally even if it was not requested as
    // an explicit matrix output.
    const bool affine_force = with_force && target_displacement != base_displacement;
    const bool need_tangent = with_tangent || affine_force;

    // The constitutive tangent C0 is required both for K_M and for the stress
    // increment Delta S used by the separate geometric operator.
    const bool need_material = need_tangent || with_geometric;

    // -----------------------------------------------------------------------------
    // constitutive history
    // -----------------------------------------------------------------------------

    // T3 owns one constitutive material point. Every evaluation reads the
    // committed state. Trial history is writable only for an explicitly
    // requested exact state update.
    const Index      state_row = this->mp_index(0);
    const Precision* old_state = &(*this->_model_data->material_state_old)(state_row, 0);
    Precision*       new_state = update_state ? &(*this->_model_data->material_state_new)(state_row, 0) : nullptr;

    // -----------------------------------------------------------------------------
    // exact strain and material response at u0
    // -----------------------------------------------------------------------------

    // The exact stretch and current direction at the linearization state are
    //
    //     lambda0 = l0 / L0,
    //     n0      = r0 / l0.
    const Precision stretch_base   = length_base / L0;
    const Vec3      direction_base = axis_base / length_base;

    // Green-Lagrange strain:
    //
    //     E0 = 1/2 (lambda0^2 - 1).
    const AxialStrain strain_base = AxialStrain::from_stretch(stretch_base);

    // Thermal expansion is evaluated independently for the base and target
    // temperature states. A null temperature denotes the material stress-free
    // temperature and therefore contributes zero free strain.
    auto material = get_material();
    const auto thermal_strain = [&](const Field* temperature_field) {
        if (!temperature_field || !material->has_thermal_expansion()) {
            return Precision(0);
        }

        const Precision T_zero = material->get_thermal_zero_temperature();
        const Precision alpha  = material->get_thermal_expansion();

        Precision temperature = Precision(0);
        for (Index node = 0; node < N; ++node) {
            temperature += (*temperature_field)(static_cast<Index>(node_ids[node]), 0);
        }

        temperature /= static_cast<Precision>(N);
        return alpha * (temperature - T_zero);
    };

    const Precision thermal_strain_base   = thermal_strain(base_temperature);
    const Precision thermal_strain_target = thermal_strain(target_temperature);

    // The complete tangent is evaluated at the thermo-mechanical base state
    //
    //     E_mech,0 = E0 - E_th(T0).
    const AxialStrain mechanical_strain_base(
        strain_base.value() - thermal_strain_base);

    AxialStressPK2 stress_base;
    Precision      material_tangent = Precision(0);

    elasticity->evaluate(
        mechanical_strain_base,
        old_state,
        new_state,
        stress_base,
        need_material ? &material_tangent : nullptr);

    // Internal force and perturbation stress use the target temperature at the
    // same base geometry:
    //
    //     E_mech,T = E0 - E_th(T).
    AxialStressPK2 stress_target_base = stress_base;
    if ((with_force || with_geometric) && target_temperature != base_temperature) {
        const AxialStrain mechanical_strain_target(
            strain_base.value() - thermal_strain_target);

        elasticity->evaluate(
            mechanical_strain_target,
            old_state,
            nullptr,
            stress_target_base,
            nullptr);
    }

    // -----------------------------------------------------------------------------
    // complete tangent stiffness at u0
    // -----------------------------------------------------------------------------

    StaticMatrix<N * 3, N * 3> tangent = StaticMatrix<N * 3, N * 3>::Zero();

    if (need_tangent) {
        // Starting from
        //
        //     f2 = A0 lambda0 S0 n0
        //
        // and using
        //
        //     lambda0 n0 = r0 / L0,
        //
        // gives
        //
        //     f2 = A0 / L0 S0 r0.
        //
        // Its variation at fixed temperature is
        //
        //     df2 = A0 / L0 [S0 I + C0 lambda0^2 (n0 tensor n0)] dr0.
        //
        // Therefore the tangent contains the material contribution
        //
        //     K_M = A0 C0 lambda0^2 / L0 (n0 tensor n0)
        //
        // and the geometric contribution generated by the base stress
        //
        //     K_G = A0 S0 / L0 I.
        const Mat3 material_block  = (A0 * material_tangent * stretch_base * stretch_base / L0) * (direction_base * direction_base.transpose());
        const Mat3 geometric_block = (A0 * stress_base.value() / L0) * Mat3::Identity();
        const Mat3 tangent_block   = material_block + geometric_block;

        // Because
        //
        //     dr0 = du2 - du1,
        //
        // the two-node truss obtains the standard block structure
        //
        //     [  K  -K ]
        //     [ -K   K ].
        tangent.block(0, 0, 3, 3) =  tangent_block;
        tangent.block(0, 3, 3, 3) = -tangent_block;
        tangent.block(3, 0, 3, 3) = -tangent_block;
        tangent.block(3, 3, 3, 3) =  tangent_block;
    }

    // -----------------------------------------------------------------------------
    // geometric stiffness generated by the stress increment
    // -----------------------------------------------------------------------------

    StaticMatrix<N * 3, N * 3> geometric = StaticMatrix<N * 3, N * 3>::Zero();

    if (with_geometric) {
        // Green-Lagrange strain can be written as
        //
        //     E = 1/2 (r.r / L0^2 - 1).
        //
        // Its first variation about r0 is
        //
        //     Delta E = r0 . Delta r / L0^2
        //
        //             = lambda0 n0 . Delta r / L0.
        const Precision strain_increment = stretch_base * direction_base.dot(delta_axis) / L0;

        // Temperature is fixed during the displacement perturbation, so
        //
        //     Delta E_th = 0
        //
        // and the constitutive law linearizes as
        //
        //     Delta S = C0 Delta E.
        //
        // Only this stress increment contributes to the separately requested
        // geometric stiffness. The base stress S0 is already contained in the
        // complete tangent K_T(u0).
        const Precision stress_increment =
            stress_target_base.value() - stress_base.value()
            + material_tangent * strain_increment;
        const Mat3 geometric_block       = (A0 * stress_increment / L0) * Mat3::Identity();

        geometric.block(0, 0, 3, 3) =  geometric_block;
        geometric.block(0, 3, 3, 3) = -geometric_block;
        geometric.block(3, 0, 3, 3) = -geometric_block;
        geometric.block(3, 3, 3, 3) =  geometric_block;
    }

    // -----------------------------------------------------------------------------
    // internal force
    // -----------------------------------------------------------------------------

    if (with_force) {
        StaticVector<N * 3> force = StaticVector<N * 3>::Zero();

        // The Total-Lagrangian internal virtual work is
        //
        //     delta W_int = A0 L0 S0 delta E.
        //
        // With
        //
        //     dE/du1 = -lambda0 n0 / L0,
        //     dE/du2 = +lambda0 n0 / L0,
        //
        // the exact base-state forces are
        //
        //     f1 = -A0 lambda0 S0 n0,
        //     f2 = +A0 lambda0 S0 n0.
        //
        // S0 already contains the thermal contribution because the material
        // response was evaluated from E_mech,0 = E0 - E_th.
        const Vec3 axial_force = A0 * stretch_base * stress_target_base.value() * direction_base;

        force.template segment<3>(0) = -axial_force;
        force.template segment<3>(3) =  axial_force;

        // For u != u0, continue the internal force linearly from the exact
        // base-state force:
        //
        //     f_int(u,T) ~= f_int(u0,T) + K_T(u0,T0) Delta u.
        if (affine_force) {
            StaticVector<N * 3> delta = StaticVector<N * 3>::Zero();
            delta.template segment<3>(0) = disp_delta.row(0).transpose();
            delta.template segment<3>(3) = disp_delta.row(1).transpose();

            force.noalias() += tangent * delta;
        }

        // Scatter the six element force components to the global nodal field.
        const Index node0 = static_cast<Index>(node_ids[0]);
        const Index node1 = static_cast<Index>(node_ids[1]);

        for (Dim d = 0; d < 3; ++d) {
            (*internal_force)(node0, d) += force(d);
            (*internal_force)(node1, d) += force(3 + d);
        }
    }

    // -----------------------------------------------------------------------------
    // requested matrix outputs
    // -----------------------------------------------------------------------------

    if (with_tangent) {
        MapMatrix mapped(tangent_buffer, N * 3, N * 3);
        mapped = tangent;
    }

    if (with_geometric) {
        MapMatrix mapped(geometric_tangent_buffer, N * 3, N * 3);
        mapped = geometric;
    }

    return with_tangent   ? MapMatrix(tangent_buffer,           N * 3, N * 3)
         : with_geometric ? MapMatrix(geometric_tangent_buffer, N * 3, N * 3)
                          : MapMatrix(nullptr, 0, 0);
}

} // namespace model
} // namespace fem