/**
 * @file generalised_isotropic_elasticity.h
 * @brief Declares isotropic normal elasticity with an independent shear modulus.
 *
 * @see Elasticity
 * @see IsotropicElasticity
 *
 * @author Finn Eggers
 * @date 07.08.2026
 */

#pragma once

#include "elasticity.h"

namespace fem::material {

/**
 * @brief Stateless generalized isotropic Hooke elasticity.
 *
 * Normal stresses use the standard isotropic coupling generated by `youngs`
 * and `poisson`; engineering shear terms use the independent `shear` modulus.
 */
struct GeneralisedIsotropicElasticity : Elasticity {
    Precision youngs;
    Precision poisson;
    Precision shear;

    GeneralisedIsotropicElasticity(Precision youngs_in,
                                   Precision poisson_in,
                                   Precision shear_in);

    bool supports_axial_linearized() const override;
    bool supports_axial_green_lagrange() const override;
    bool supports_volume_linearized() const override;
    bool supports_volume_green_lagrange() const override;
    bool supports_shell_integration_linearized() const override;
    bool supports_shell_integration_green_lagrange() const override;

    void evaluate(const AxialStrainLinearized& strain,
                  const Precision*             state,
                  AxialStressCauchy&           stress,
                  Precision&                   tangent) const override;

    void evaluate(const AxialStrainGreenLagrange& strain,
                  const Precision*                  state,
                  AxialStressPK2&                 stress,
                  Precision&                     tangent) const override;

    void evaluate(const VolumeStrainLinearized& strain,
                  const Precision*              state,
                  VolumeStressCauchy&           stress,
                  Mat6&                         tangent) const override;

    void evaluate(const VolumeStrainGreenLagrange& strain,
                  const Precision*                   state,
                  VolumeStressPK2&                 stress,
                  Mat6&                           tangent) const override;

    void evaluate(const ShellMaterialStrainLinearized& strain,
                  const Precision*                     state,
                  ShellMaterialStressCauchy&            stress,
                  Mat5&                               tangent) const override;

    void evaluate(const ShellMaterialStrainGreenLagrange& strain,
                  const Precision*                          state,
                  ShellMaterialStressPK2&                 stress,
                  Mat5&                                  tangent) const override;

private:
    [[nodiscard]] Mat3 plane_stress_tangent() const;
    [[nodiscard]] Mat5 shell_material_tangent() const;
    [[nodiscard]] Mat6 volume_tangent() const;
};

} // namespace fem::material
