/**
 * @file generalised_isotropic_elasticity.h
 * @brief Declares isotropic normal elasticity with an independent shear modulus.
 *
 * The generalized isotropic model retains the volumetric and normal coupling
 * implied by Young's modulus and Poisson's ratio while allowing the engineering
 * shear modulus to be prescribed independently. It supports axial, solid and
 * shell material evaluation through the common elasticity interface.
 *
 * @see Elasticity
 * @see IsotropicElasticity
 *
 * @author Finn Eggers
 * @date 07.08.2026
 */

#pragma once

#include "elasticity.h"

namespace fem::material {

/**
 * @brief Stateless generalized isotropic Hooke elasticity.
 *
 * Normal stresses use the standard isotropic coupling generated by `youngs`
 * and `poisson`. Engineering shear terms use the independent `shear` modulus
 * in three-dimensional and shell tangents. Responses are evaluated in the
 * material basis supplied by the owning section.
 *
 * The constitutive law contains no history variables and never uses the
 * material-point state pointers passed through `Elasticity`.
 */
struct GeneralisedIsotropicElasticity : Elasticity {
    // Independent elastic parameters
    Precision youngs;
    Precision poisson;
    Precision shear;

    // Construct normal coupling from Young's modulus and Poisson's ratio while
    // retaining the explicitly supplied engineering shear modulus.
    GeneralisedIsotropicElasticity(Precision youngs_in,
                                   Precision poisson_in,
                                   Precision shear_in);

    // Advertise all axial, volume and shell strain measures implemented below.
    // The law is linear in every supplied strain measure and contains no state.
    bool supports_axial_linearized() const override;
    bool supports_axial_green_lagrange() const override;
    bool supports_volume_linearized() const override;
    bool supports_volume_green_lagrange() const override;
    bool supports_shell_integration_linearized() const override;
    bool supports_shell_integration_green_lagrange() const override;

    // Linearized axial response sigma = E epsilon. Independent shear stiffness
    // does not enter this one-dimensional reduction; the tangent is optional.
    void evaluate(const AxialStrainLinearized& strain,
                  const Precision*             old_state,
                  Precision*                   new_state,
                  AxialStressCauchy&           stress,
                  Precision*                   tangent = nullptr) const override;

    // Total-Lagrangian axial response S = E E_GL with optional constant tangent E.
    void evaluate(const AxialStrainGreenLagrange& strain,
                  const Precision*                old_state,
                  Precision*                      new_state,
                  AxialStressPK2&                 stress,
                  Precision*                      tangent = nullptr) const override;

    // Linearized three-dimensional response. Normal entries follow isotropic
    // E/nu coupling, while all engineering shear diagonals use the supplied G.
    void evaluate(const VolumeStrainLinearized& strain,
                  const Precision*              old_state,
                  Precision*                    new_state,
                  VolumeStressCauchy&           stress,
                  Mat6*                         tangent = nullptr) const override;

    // Finite-strain response with the identical constant material operator,
    // interpreted as the mapping from Green-Lagrange strain to PK2 stress.
    void evaluate(const VolumeStrainGreenLagrange& strain,
                  const Precision*                 old_state,
                  Precision*                       new_state,
                  VolumeStressPK2&                 stress,
                  Mat6*                            tangent = nullptr) const override;

    // Linearized shell plane-stress response. The in-plane normal block uses
    // E and nu; in-plane and transverse engineering shear terms use G.
    void evaluate(const ShellMaterialStrainLinearized& strain,
                  const Precision*                     old_state,
                  Precision*                           new_state,
                  ShellMaterialStressCauchy&            stress,
                  Mat5*                                tangent = nullptr) const override;

    // Finite-strain shell response returning PK2 components. The reduced
    // material derivative is written only when requested.
    void evaluate(const ShellMaterialStrainGreenLagrange& strain,
                  const Precision*                        old_state,
                  Precision*                              new_state,
                  ShellMaterialStressPK2&                 stress,
                  Mat5*                                   tangent = nullptr) const override;

private:
    // Build the generalized-isotropic in-plane plane-stress operator.
    [[nodiscard]] Mat3 plane_stress_tangent() const;

    // Embed in-plane and transverse shear terms in shell material ordering.
    [[nodiscard]] Mat5 shell_material_tangent() const;

    // Build the three-dimensional normal-coupling and independent-shear tangent.
    [[nodiscard]] Mat6 volume_tangent() const;
};

} // namespace fem::material
