/**
 * @file generalised_isotropic_elasticity.h
 * @brief Declares isotropic normal elasticity with an independent shear modulus.
 *
 * The generalized isotropic model retains the volumetric and normal coupling
 * implied by Young's modulus and Poisson's ratio while allowing the engineering
 * shear modulus to be prescribed independently. It supports axial, solid and
 * shell material evaluation through the common elasticity interface.
 *
 * @see Elasticity
 * @see IsotropicElasticity
 *
 * @author Finn Eggers
 * @date 07.08.2026
 */

#pragma once

#include "elasticity.h"

namespace fem::material {

/**
 * @brief Stateless generalized isotropic Hooke elasticity.
 *
 * Normal stresses use the standard isotropic coupling generated by `youngs`
 * and `poisson`. Engineering shear terms use the independent `shear` modulus
 * in three-dimensional and shell tangents. Responses are evaluated in the
 * material basis supplied by the owning section.
 *
 * The constitutive law contains no history variables and never modifies the
 * material-point state pointer passed through `Elasticity`.
 */
struct GeneralisedIsotropicElasticity : Elasticity {
    // Independent elastic parameters
    Precision youngs;
    Precision poisson;
    Precision shear;

    // Construct normal coupling from Young's modulus and Poisson's ratio while
    // retaining the explicitly supplied engineering shear modulus.
    GeneralisedIsotropicElasticity(Precision youngs_in,
                                   Precision poisson_in,
                                   Precision shear_in);

    // Advertise all axial, volume and shell strain measures implemented below.
    // The law is linear in every supplied strain measure and contains no state.
    bool supports_axial_linearized() const override;
    bool supports_axial_green_lagrange() const override;
    bool supports_volume_linearized() const override;
    bool supports_volume_green_lagrange() const override;
    bool supports_shell_integration_linearized() const override;
    bool supports_shell_integration_green_lagrange() const override;

    // Linearized axial response sigma = E epsilon. Independent shear stiffness
    // does not enter this one-dimensional reduction; state remains unchanged.
    void evaluate(const AxialStrainLinearized& strain,
                  Precision*                   state,
                  AxialStressCauchy&           stress,
                  Precision&                   tangent) const override;

    // Total-Lagrangian axial response S = E E_GL with constant tangent E.
    // The returned PK2 stress is work-conjugate to Green-Lagrange strain.
    void evaluate(const AxialStrainGreenLagrange& strain,
                  Precision*                      state,
                  AxialStressPK2&                 stress,
                  Precision&                      tangent) const override;

    // Linearized three-dimensional response. Normal entries follow isotropic
    // E/nu coupling, while all engineering shear diagonals use the supplied G.
    void evaluate(const VolumeStrainLinearized& strain,
                  Precision*                    state,
                  VolumeStressCauchy&           stress,
                  Mat6&                         tangent) const override;

    // Finite-strain response with the identical constant material operator,
    // interpreted as the mapping from Green-Lagrange strain to PK2 stress.
    void evaluate(const VolumeStrainGreenLagrange& strain,
                  Precision*                       state,
                  VolumeStressPK2&                 stress,
                  Mat6&                            tangent) const override;

    // Linearized shell plane-stress response. The in-plane normal block uses
    // E and nu; in-plane and transverse engineering shear terms use G.
    void evaluate(const ShellMaterialStrainLinearized& strain,
                  Precision*                           state,
                  ShellMaterialStressCauchy&            stress,
                  Mat5&                                 tangent) const override;

    // Finite-strain shell response returning PK2 components and their constant
    // derivative with respect to five-component Green-Lagrange shell strain.
    void evaluate(const ShellMaterialStrainGreenLagrange& strain,
                  Precision*                              state,
                  ShellMaterialStressPK2&                 stress,
                  Mat5&                                   tangent) const override;

private:
    // Build the generalized-isotropic in-plane plane-stress operator.
    [[nodiscard]] Mat3 plane_stress_tangent() const;

    // Embed in-plane and transverse shear terms in shell material ordering.
    [[nodiscard]] Mat5 shell_material_tangent() const;

    // Build the three-dimensional normal-coupling and independent-shear tangent.
    [[nodiscard]] Mat6 volume_tangent() const;
};

} // namespace fem::material
