// -----------------------------------------------------------------------------
// Finite-strain return map and consistent tangent
// -----------------------------------------------------------------------------

/**
 * @brief Spectral data of the symmetric exponential exp(A).
 *
 * The finite plastic update uses a symmetric deviatoric increment A. Keeping the
 * eigensystem of A together with exp(A) allows the exact Fréchet derivative
 * Dexp(A)[dA] to reuse the same spectral decomposition when the local Newton
 * Jacobian and the consistent material tangent are assembled.
 */
struct SymmetricExponential {
    Mat3 value           = Mat3::Identity();
    Mat3 eigenvectors    = Mat3::Identity();
    Vec3 eigenvalues     = Vec3::Zero();
    Vec3 exp_eigenvalues = Vec3::Ones();
};

/**
 * @brief Complete constitutive point generated by one local return-map iterate.
 *
 * The local unknown vector is
 *
 *     x = [A11, A22, A23, A13, A12, dgamma],
 *
 * where A is symmetric and deviatoric, hence
 *
 *     A33 = -A11 - A22.
 *
 * This structure contains only quantities derived from the current local iterate;
 * none of them are persistent history variables.
 */
struct FinitePoint {
    Mat3 A      = Mat3::Zero();
    SymmetricExponential exp_A;
    Mat3 Fp     = Mat3::Identity();
    Mat3 Fp_inv = Mat3::Identity();
    Mat3 Ce     = Mat3::Identity();
    Mat3 Se     = Mat3::Zero();
    Mat3 M      = Mat3::Zero();
    Mat3 m      = Mat3::Zero();
    Mat3 N      = Mat3::Zero();
    Precision q = Precision(0);
};

/**
 * @brief Result of one complete finite-strain constitutive update.
 *
 * The converged stress is stored through the generic VolumeStress representation.
 * C, Fp_old, alpha_old and the converged local unknown x are retained only because
 * the analytically consistent tangent linearizes exactly the same converged return
 * map afterwards.
 */
struct FiniteResponse {
    VolumeStress stress;
    Mat3 C              = Mat3::Identity();
    Mat3 Fp_old         = Mat3::Identity();
    Precision alpha_old = Precision(0);
    Vec6 x              = Vec6::Zero();
    FinitePoint point;
    bool plastic        = false;
};

/**
 * @brief Directional derivative of PK2 stress and local return-map residual.
 */
struct DirectionalResponse {
    VolumeStress d_stress;
    Vec6 d_residual = Vec6::Zero();
};

/**
 * @brief Local Jacobian blocks required by Newton and the consistent tangent.
 *
 * residual_x = dR/dx and stress_x = dS/dx are both exact analytical derivatives
 * of the discrete finite-strain return map.
 */
struct LocalLinearization {
    Mat6 residual_x = Mat6::Zero();
    Mat6 stress_x   = Mat6::Zero();
};

/**
 * @brief Evaluates all tensor quantities for one local finite-plasticity iterate.
 *
 * Starting from the committed plastic deformation Fp_n and local increment A, the
 * multiplicative update is
 *
 *     Fp_{n+1} = exp(A) Fp_n.
 *
 * The supplied total Green-Lagrange strain E defines
 *
 *     C = I + 2 E.
 *
 * The elastic metric, elastic Green-Lagrange strain and elastic PK2-like stress in
 * the intermediate configuration are then
 *
 *     Ce = Fp^{-T} C Fp^{-1}
 *     Ee = 1/2 (Ce - I)
 *     Se = lambda tr(Ee) I + 2 G Ee.
 *
 * The Mandel stress and J2 quantities are
 *
 *     M = sym(Ce Se)
 *     m = dev(M)
 *     q = sqrt(3/2 m:m)
 *     N = 3/2 m/q.
 *
 * @param C Total right Cauchy-Green metric I + 2 E.
 * @param Fp_old Committed plastic deformation chosen as sqrt(Cp_n).
 * @param x Current six-component local Newton unknown.
 * @param shear Elastic shear modulus G.
 * @param bulk Elastic bulk modulus K.
 * @return Fully evaluated local constitutive point.
 */
FinitePoint finite_point(const Mat3& C,
                         const Mat3& Fp_old,
                         const Vec6& x,
                         Precision shear,
                         Precision bulk) {
    FinitePoint point;

    // -------------------------------------------------------------------------
    // Reconstruct the symmetric trace-free tensor A from its five independent
    // local components. The ordering is deliberately written out here so the
    // parameterization is visible where it is used.
    // -------------------------------------------------------------------------
    point.A << x(0), x(4), x(3),
               x(4), x(1), x(2),
               x(3), x(2), -x(0) - x(1);
    point.A = Precision(0.5) * (point.A + point.A.transpose());

    // -------------------------------------------------------------------------
    // Compute exp(A) spectrally.
    //
    // A is symmetric, so
    //
    //     A      = Q diag(a_i) Q^T
    //     exp(A) = Q diag(exp(a_i)) Q^T.
    //
    // The eigenpairs are retained because Dexp(A)[dA] is required later.
    // -------------------------------------------------------------------------
    Eigen::SelfAdjointEigenSolver<Mat3> exp_solver(point.A);
    logging::error(exp_solver.info() == Eigen::Success,
        "J2: eigendecomposition failed during symmetric exponential");

    point.exp_A.eigenvalues  = exp_solver.eigenvalues();
    point.exp_A.eigenvectors = exp_solver.eigenvectors();
    point.exp_A.exp_eigenvalues(0) = std::exp(point.exp_A.eigenvalues(0));
    point.exp_A.exp_eigenvalues(1) = std::exp(point.exp_A.eigenvalues(1));
    point.exp_A.exp_eigenvalues(2) = std::exp(point.exp_A.eigenvalues(2));

    point.exp_A.value = point.exp_A.eigenvectors
                      * point.exp_A.exp_eigenvalues.asDiagonal()
                      * point.exp_A.eigenvectors.transpose();
    point.exp_A.value = Precision(0.5)
                      * (point.exp_A.value + point.exp_A.value.transpose());

    // -------------------------------------------------------------------------
    // Apply the multiplicative plastic update and construct the elastic metric.
    // -------------------------------------------------------------------------
    point.Fp     = point.exp_A.value * Fp_old;
    point.Fp_inv = point.Fp.inverse();

    point.Ce = point.Fp_inv.transpose() * C * point.Fp_inv;
    point.Ce = Precision(0.5) * (point.Ce + point.Ce.transpose());

    // Ce must remain symmetric positive definite. The check is kept directly at
    // the construction site because loss of positive definiteness means the local
    // iterate has left the admissible finite-strain domain.
    Eigen::SelfAdjointEigenSolver<Mat3> ce_solver(
        point.Ce, Eigen::EigenvaluesOnly
    );
    logging::error(ce_solver.info() == Eigen::Success,
        "J2: eigendecomposition failed for elastic metric");

    const Vec3 ce_eigenvalues = ce_solver.eigenvalues();
    const Precision ce_scale = std::max(
        Precision(1), ce_eigenvalues.cwiseAbs().maxCoeff()
    );
    logging::error(ce_eigenvalues.minCoeff()
                   > Precision(100) * std::numeric_limits<Precision>::epsilon() * ce_scale,
        "J2: elastic metric is not positive definite");

    // -------------------------------------------------------------------------
    // Saint-Venant-Kirchhoff elasticity in the intermediate configuration.
    //
    //     Ee     = 1/2 (Ce - I)
    //     lambda = K - 2/3 G
    //     Se     = lambda tr(Ee) I + 2 G Ee.
    // -------------------------------------------------------------------------
    const Mat3 Ee = Precision(0.5) * (point.Ce - Mat3::Identity());
    const Precision lame = bulk - Precision(2.0 / 3.0) * shear;

    point.Se = lame * Ee.trace() * Mat3::Identity()
             + Precision(2) * shear * Ee;
    point.Se = Precision(0.5) * (point.Se + point.Se.transpose());

    // -------------------------------------------------------------------------
    // Mandel stress and associative J2 flow direction.
    //
    //     M = sym(Ce Se)
    //     m = M - 1/3 tr(M) I
    //     q = sqrt(3/2 m:m)
    //     N = 3/2 m/q.
    // -------------------------------------------------------------------------
    point.M = point.Ce * point.Se;
    point.M = Precision(0.5) * (point.M + point.M.transpose());

    point.m = point.M
            - (point.M.trace() / Precision(3)) * Mat3::Identity();

    point.q = std::sqrt(std::max(
        Precision(0),
        Precision(1.5) * (point.m.array() * point.m.array()).sum()
    ));

    if (point.q > Precision(0)) {
        point.N = (Precision(1.5) / point.q) * point.m;
    }

    return point;
}

/**
 * @brief Differentiates the finite-strain constitutive equations analytically.
 *
 * This routine is the central analytical linearization used by both the local
 * return-map Newton system and the global algorithmic tangent. The supplied
 * directions dC, dA and dgamma are independent directional variations.
 *
 * The exponential update is differentiated with the exact Fréchet derivative
 * of the matrix exponential. For symmetric A = Q diag(a_i) Q^T,
 *
 *     Q^T Dexp(A)[dA] Q = L_exp .* (Q^T dA Q),
 *
 * where
 *
 *     L_ii = exp(a_i)
 *
 * and for i != j
 *
 *     L_ij = (exp(a_i) - exp(a_j)) / (a_i - a_j).
 *
 * From dFp the remaining derivatives follow by direct chain rule,
 *
 *     dFp_inv = -Fp_inv dFp Fp_inv
 *
 *     dCe = sym(dFp_inv^T C Fp_inv
 *             + Fp_inv^T dC Fp_inv
 *             + Fp_inv^T C dFp_inv)
 *
 *     dSe = lambda tr(dEe) I + 2 G dEe
 *
 *     dM  = sym(dCe Se + Ce dSe)
 *
 *     dq  = N : dev(dM)
 *
 *     dN  = 3/(2q) [dev(dM) - (dq/q) m].
 *
 * The PK2 stress in the reference configuration is
 *
 *     S = Fp_inv Se Fp_inv^T,
 *
 * and is differentiated by the product rule. When requested, the six local
 * residual equations are differentiated at the same time.
 *
 * @param point Current converged or Newton-iterate constitutive point.
 * @param C Current total right Cauchy-Green metric.
 * @param Fp_old Committed plastic deformation.
 * @param alpha_old Committed equivalent plastic strain.
 * @param x Current local unknown vector [A components, dgamma].
 * @param dC Directional variation of C.
 * @param dA Directional variation of A.
 * @param dgamma Directional variation of the plastic multiplier increment.
 * @param shear Elastic shear modulus G.
 * @param bulk Elastic bulk modulus K.
 * @param yield_curve Isotropic hardening table.
 * @param with_residual Whether dR is required in addition to dS.
 * @return Analytical directional stress and residual derivatives.
 */
DirectionalResponse directional_response(const FinitePoint& point,
                                         const Mat3& C,
                                         const Mat3& Fp_old,
                                         Precision alpha_old,
                                         const Vec6& x,
                                         const Mat3& dC,
                                         const Mat3& dA,
                                         Precision dgamma,
                                         Precision shear,
                                         Precision bulk,
                                         const YieldCurve& yield_curve,
                                         bool with_residual) {
    // -------------------------------------------------------------------------
    // Exact Fréchet derivative Dexp(A)[dA].
    //
    // Transform dA to the eigenbasis of A, multiply each component by the
    // exponential divided difference, and transform the result back.
    // -------------------------------------------------------------------------
    const Mat3 local_direction = point.exp_A.eigenvectors.transpose()
                               * (Precision(0.5) * (dA + dA.transpose()))
                               * point.exp_A.eigenvectors;

    Mat3 local_exponential_derivative = Mat3::Zero();

    for (Index i = 0; i < 3; ++i) {
        for (Index j = 0; j < 3; ++j) {
            Precision divided_difference;

            if (i == j) {
                divided_difference = point.exp_A.exp_eigenvalues(i);
            } else {
                const Precision ai = point.exp_A.eigenvalues(i);
                const Precision aj = point.exp_A.eigenvalues(j);
                const Precision delta = ai - aj;
                const Precision scale = std::max({
                    Precision(1), std::abs(ai), std::abs(aj)
                });

                // For repeated or nearly repeated eigenvalues use the exact
                // limit of the divided difference. Otherwise expm1 evaluates
                // exp(delta) - 1 accurately when delta is small.
                if (std::abs(delta)
                    <= Precision(64) * std::numeric_limits<Precision>::epsilon() * scale) {
                    divided_difference = Precision(0.5)
                        * (point.exp_A.exp_eigenvalues(i)
                           + point.exp_A.exp_eigenvalues(j));
                } else {
                    divided_difference = point.exp_A.exp_eigenvalues(j)
                                       * std::expm1(delta) / delta;
                }
            }

            local_exponential_derivative(i, j) =
                divided_difference * local_direction(i, j);
        }
    }

    Mat3 dplastic_increment = point.exp_A.eigenvectors
                            * local_exponential_derivative
                            * point.exp_A.eigenvectors.transpose();
    dplastic_increment = Precision(0.5)
                       * (dplastic_increment + dplastic_increment.transpose());

    // -------------------------------------------------------------------------
    // Differentiate the multiplicative plastic update and its inverse.
    //
    //     Fp     = exp(A) Fp_old
    //     dFp    = Dexp(A)[dA] Fp_old
    //     dFp^-1 = -Fp^-1 dFp Fp^-1.
    // -------------------------------------------------------------------------
    const Mat3 dFp = dplastic_increment * Fp_old;
    const Mat3 dFp_inv = -point.Fp_inv * dFp * point.Fp_inv;

    // -------------------------------------------------------------------------
    // Differentiate the elastic metric Ce = Fp^-T C Fp^-1.
    // -------------------------------------------------------------------------
    Mat3 dCe = dFp_inv.transpose() * C * point.Fp_inv
             + point.Fp_inv.transpose() * dC * point.Fp_inv
             + point.Fp_inv.transpose() * C * dFp_inv;
    dCe = Precision(0.5) * (dCe + dCe.transpose());

    // -------------------------------------------------------------------------
    // Differentiate the elastic stress law in the intermediate configuration.
    // -------------------------------------------------------------------------
    const Mat3 dEe = Precision(0.5) * dCe;
    const Precision lame = bulk - Precision(2.0 / 3.0) * shear;

    Mat3 dSe = lame * dEe.trace() * Mat3::Identity()
             + Precision(2) * shear * dEe;
    dSe = Precision(0.5) * (dSe + dSe.transpose());

    // -------------------------------------------------------------------------
    // Differentiate Mandel stress, equivalent stress, and flow direction.
    // -------------------------------------------------------------------------
    Mat3 dM = dCe * point.Se + point.Ce * dSe;
    dM = Precision(0.5) * (dM + dM.transpose());

    const Mat3 dm = dM - (dM.trace() / Precision(3)) * Mat3::Identity();

    Precision dq = Precision(0);
    Mat3 dN = Mat3::Zero();

    if (point.q > Precision(0)) {
        dq = (point.N.array() * dm.array()).sum();

        dN = (Precision(1.5) / point.q)
           * (dm - (dq / point.q) * point.m);
    }

    // -------------------------------------------------------------------------
    // Differentiate the reference PK2 stress
    //
    //     S = Fp^-1 Se Fp^-T.
    // -------------------------------------------------------------------------
    Mat3 dstress = dFp_inv * point.Se * point.Fp_inv.transpose()
                 + point.Fp_inv * dSe * point.Fp_inv.transpose()
                 + point.Fp_inv * point.Se * dFp_inv.transpose();
    dstress = Precision(0.5) * (dstress + dstress.transpose());

    DirectionalResponse result;
    result.d_stress = VolumeStress(dstress);

    if (!with_residual) {
        return result;
    }

    logging::error(point.q > Precision(0),
        "J2: cannot differentiate plastic residual at zero Mandel stress");

    // -------------------------------------------------------------------------
    // Differentiate the five flow equations
    //
    //     R_A = A - dgamma N = 0.
    //
    // Hence
    //
    //     dR_A = dA - d(dgamma) N - dgamma dN.
    //
    // Only five independent components are stored because R_A is deviatoric.
    // -------------------------------------------------------------------------
    Mat3 dflow_residual = dA - dgamma * point.N - x(5) * dN;
    dflow_residual -= (dflow_residual.trace() / Precision(3)) * Mat3::Identity();

    result.d_residual(0) = dflow_residual(0, 0);
    result.d_residual(1) = dflow_residual(1, 1);
    result.d_residual(2) = dflow_residual(1, 2);
    result.d_residual(3) = dflow_residual(0, 2);
    result.d_residual(4) = dflow_residual(0, 1);

    // -------------------------------------------------------------------------
    // Differentiate the scalar consistency equation.
    //
    // The residual is scaled by (3 G + H),
    //
    //     R_gamma = [q - sigma_y(alpha_n + dgamma)] / (3 G + H).
    //
    // Inside one active hardening segment H is constant, therefore
    //
    //     dR_gamma = [dq - H d(dgamma)] / (3 G + H).
    // -------------------------------------------------------------------------
    const Precision alpha = alpha_old + x(5);
    const Precision hardening = hardening_slope_at(yield_curve, alpha);

    result.d_residual(5) = (dq - hardening * dgamma)
                         / (Precision(3) * shear + hardening);

    return result;
}

/**
 * @brief Builds the exact local Jacobian dR/dx and stress derivative dS/dx.
 *
 * The first five columns correspond to the five independent components of the
 * symmetric deviatoric tensor A. The final column corresponds to dgamma. Each
 * column is obtained by passing the exact local basis direction through
 * directional_response(); no finite differences or perturbed return maps are used.
 *
 * @param point Current constitutive point.
 * @param C Current total right Cauchy-Green metric.
 * @param Fp_old Committed plastic deformation.
 * @param alpha_old Committed equivalent plastic strain.
 * @param x Current local unknown vector.
 * @param shear Elastic shear modulus G.
 * @param bulk Elastic bulk modulus K.
 * @param yield_curve Isotropic hardening table.
 * @return Exact local residual and stress Jacobian blocks.
 */
LocalLinearization local_linearization(const FinitePoint& point,
                                       const Mat3& C,
                                       const Mat3& Fp_old,
                                       Precision alpha_old,
                                       const Vec6& x,
                                       Precision shear,
                                       Precision bulk,
                                       const YieldCurve& yield_curve) {
    LocalLinearization result;

    for (Index column = 0; column < 6; ++column) {
        // ---------------------------------------------------------------------
        // Build the exact tensor basis dA for one local unknown.
        //
        // x = [A11, A22, A23, A13, A12, dgamma]
        //
        // and A33 = -A11 - A22 enforces tr(A)=0.
        // ---------------------------------------------------------------------
        Mat3 dA = Mat3::Zero();
        Precision dgamma = Precision(0);

        if (column == 0) {
            dA(0, 0) = Precision(1);
            dA(2, 2) = Precision(-1);
        } else if (column == 1) {
            dA(1, 1) = Precision(1);
            dA(2, 2) = Precision(-1);
        } else if (column == 2) {
            dA(1, 2) = Precision(1);
            dA(2, 1) = Precision(1);
        } else if (column == 3) {
            dA(0, 2) = Precision(1);
            dA(2, 0) = Precision(1);
        } else if (column == 4) {
            dA(0, 1) = Precision(1);
            dA(1, 0) = Precision(1);
        } else {
            dgamma = Precision(1);
        }

        const DirectionalResponse derivative = directional_response(
            point,
            C,
            Fp_old,
            alpha_old,
            x,
            Mat3::Zero(),
            dA,
            dgamma,
            shear,
            bulk,
            yield_curve,
            true
        );

        result.residual_x.col(column) = derivative.d_residual;
        result.stress_x.col(column)   = derivative.d_stress.voigt();
    }

    return result;
}

/**
 * @brief Integrates the multiplicative finite-strain J2 model from committed history.
 *
 * Persistent history is represented by Cp_n and alpha_n. Because isotropic J2
 * plasticity is insensitive to plastic rotation, a convenient representative of
 * Fp_n is chosen as the symmetric positive-definite square root
 *
 *     Fp_n = sqrt(Cp_n).
 *
 * For a plastic trial state the local unknowns A and dgamma are determined from
 * six backward-Euler equations,
 *
 *     A - dgamma N = 0
 *     q - sigma_y(alpha_n + dgamma) = 0.
 *
 * Newton uses the exact analytical dR/dx supplied by local_linearization(). After
 * convergence the physical state is written directly back into the supplied state
 * vector as Cp_{n+1} and alpha_{n+1}.
 *
 * @param green_lagrange Generic VolumeStrain containing Green-Lagrange components.
 * @param state Working copy of the committed seven-component state, overwritten by
 *              the converged candidate state.
 * @param shear Elastic shear modulus G.
 * @param bulk Elastic bulk modulus K.
 * @param yield_curve Piecewise-linear isotropic hardening law.
 * @return Converged finite-strain constitutive response.
 */
FiniteResponse integrate_finite_strain(const VolumeStrain& green_lagrange,
                                       State& state,
                                       Precision shear,
                                       Precision bulk,
                                       const YieldCurve& yield_curve) {
    FiniteResponse result;

    // -------------------------------------------------------------------------
    // Construct the total right Cauchy-Green metric from Green-Lagrange strain.
    //
    //     E = 1/2 (C - I)
    //
    // therefore
    //
    //     C = I + 2 E.
    // -------------------------------------------------------------------------
    result.C = Mat3::Identity() + Precision(2) * green_lagrange.tensor();
    result.C = Precision(0.5) * (result.C + result.C.transpose());

    Eigen::SelfAdjointEigenSolver<Mat3> c_solver(
        result.C, Eigen::EigenvaluesOnly
    );
    logging::error(c_solver.info() == Eigen::Success,
        "J2: eigendecomposition failed for total metric");

    const Vec3 c_eigenvalues = c_solver.eigenvalues();
    const Precision c_scale = std::max(
        Precision(1), c_eigenvalues.cwiseAbs().maxCoeff()
    );
    logging::error(c_eigenvalues.minCoeff()
                   > Precision(100) * std::numeric_limits<Precision>::epsilon() * c_scale,
        "J2: total metric is not positive definite");

    // -------------------------------------------------------------------------
    // Reconstruct the committed plastic metric directly from the state vector.
    // -------------------------------------------------------------------------
    Mat3 Cp_old;
    Cp_old << state[0], state[5], state[4],
              state[5], state[1], state[3],
              state[4], state[3], state[2];
    Cp_old = Precision(0.5) * (Cp_old + Cp_old.transpose());

    result.alpha_old = state[eqp_index];

    // -------------------------------------------------------------------------
    // Choose Fp_n = sqrt(Cp_n).
    //
    // Isotropic plasticity does not depend on plastic rotation, so the symmetric
    // positive-definite square root is a valid and convenient representative.
    // -------------------------------------------------------------------------
    Eigen::SelfAdjointEigenSolver<Mat3> cp_solver(Cp_old);
    logging::error(cp_solver.info() == Eigen::Success,
        "J2: eigendecomposition failed for committed plastic metric");

    const Vec3 cp_eigenvalues = cp_solver.eigenvalues();
    const Precision cp_scale = std::max(
        Precision(1), cp_eigenvalues.cwiseAbs().maxCoeff()
    );
    logging::error(cp_eigenvalues.minCoeff()
                   > Precision(100) * std::numeric_limits<Precision>::epsilon() * cp_scale,
        "J2: committed plastic metric is not positive definite");

    Vec3 sqrt_cp_eigenvalues;
    sqrt_cp_eigenvalues(0) = std::sqrt(cp_eigenvalues(0));
    sqrt_cp_eigenvalues(1) = std::sqrt(cp_eigenvalues(1));
    sqrt_cp_eigenvalues(2) = std::sqrt(cp_eigenvalues(2));

    result.Fp_old = cp_solver.eigenvectors()
                  * sqrt_cp_eigenvalues.asDiagonal()
                  * cp_solver.eigenvectors().transpose();
    result.Fp_old = Precision(0.5)
                  * (result.Fp_old + result.Fp_old.transpose());

    // -------------------------------------------------------------------------
    // Evaluate the elastic trial state x = 0.
    // -------------------------------------------------------------------------
    result.x.setZero();
    result.point = finite_point(
        result.C, result.Fp_old, result.x, shear, bulk
    );

    const Precision yield_old = yield_stress_at(yield_curve, result.alpha_old);
    const Precision f_trial   = result.point.q - yield_old;

    result.plastic = f_trial
        > stress_tolerance(Precision(3) * bulk, initial_yield_stress(yield_curve));

    // -------------------------------------------------------------------------
    // Plastic local Newton solve.
    // -------------------------------------------------------------------------
    if (result.plastic) {
        logging::error(result.point.q > Precision(0),
            "J2: positive yield residual with zero trial Mandel stress");

        bool converged = false;

        for (Index iteration = 0; iteration < 30; ++iteration) {
            const FinitePoint point = finite_point(
                result.C, result.Fp_old, result.x, shear, bulk
            );

            // -----------------------------------------------------------------
            // Assemble the six local backward-Euler residual equations directly.
            //
            // Flow residual:
            //
            //     R_A = A - dgamma N.
            //
            // Consistency residual:
            //
            //     R_gamma = [q - sigma_y(alpha_n + dgamma)] / (3 G + H).
            //
            // The scalar equation is scaled only to balance the local system; its
            // zero is unchanged.
            // -----------------------------------------------------------------
            Mat3 flow_residual_tensor = point.A - result.x(5) * point.N;
            flow_residual_tensor -=
                (flow_residual_tensor.trace() / Precision(3)) * Mat3::Identity();

            Vec6 residual = Vec6::Zero();
            residual(0) = flow_residual_tensor(0, 0);
            residual(1) = flow_residual_tensor(1, 1);
            residual(2) = flow_residual_tensor(1, 2);
            residual(3) = flow_residual_tensor(0, 2);
            residual(4) = flow_residual_tensor(0, 1);

            const Precision alpha = result.alpha_old + result.x(5);
            const Precision hardening = hardening_slope_at(yield_curve, alpha);
            residual(5) = (point.q - yield_stress_at(yield_curve, alpha))
                        / (Precision(3) * shear + hardening);

            if (residual.cwiseAbs().maxCoeff() <= Precision(1e-10)) {
                result.point = point;
                converged = true;
                break;
            }

            // -----------------------------------------------------------------
            // Newton correction from the exact local Jacobian.
            // -----------------------------------------------------------------
            const LocalLinearization linearization = local_linearization(
                point,
                result.C,
                result.Fp_old,
                result.alpha_old,
                result.x,
                shear,
                bulk,
                yield_curve
            );

            Eigen::FullPivLU<Mat6> lu(linearization.residual_x);
            logging::error(lu.isInvertible(),
                "J2: singular local finite-plasticity Jacobian");

            const Vec6 delta = lu.solve(-residual);

            // -----------------------------------------------------------------
            // Local line search.
            //
            // The analytical Newton direction is retained, but the step length is
            // reduced when necessary to keep dgamma non-negative and to obtain a
            // strict reduction of the local residual norm.
            // -----------------------------------------------------------------
            Precision scale = Precision(1);
            bool accepted = false;
            const Precision residual_norm = residual.norm();

            while (scale >= Precision(1e-8)) {
                const Vec6 candidate_x = result.x + scale * delta;

                if (candidate_x(5) >= Precision(0)) {
                    const FinitePoint candidate_point = finite_point(
                        result.C, result.Fp_old, candidate_x, shear, bulk
                    );

                    Mat3 candidate_flow_residual = candidate_point.A
                                                - candidate_x(5) * candidate_point.N;
                    candidate_flow_residual -=
                        (candidate_flow_residual.trace() / Precision(3))
                        * Mat3::Identity();

                    Vec6 candidate_residual = Vec6::Zero();
                    candidate_residual(0) = candidate_flow_residual(0, 0);
                    candidate_residual(1) = candidate_flow_residual(1, 1);
                    candidate_residual(2) = candidate_flow_residual(1, 2);
                    candidate_residual(3) = candidate_flow_residual(0, 2);
                    candidate_residual(4) = candidate_flow_residual(0, 1);

                    const Precision candidate_alpha =
                        result.alpha_old + candidate_x(5);
                    const Precision candidate_hardening =
                        hardening_slope_at(yield_curve, candidate_alpha);

                    candidate_residual(5) =
                        (candidate_point.q
                         - yield_stress_at(yield_curve, candidate_alpha))
                        / (Precision(3) * shear + candidate_hardening);

                    if (candidate_residual.norm() < residual_norm) {
                        result.x = candidate_x;
                        accepted = true;
                        break;
                    }
                }

                scale *= Precision(0.5);
            }

            logging::error(accepted,
                "J2: finite-plasticity local Newton line search failed");
        }

        logging::error(converged,
            "J2: finite-plasticity local return mapping did not converge");
    }

    // -------------------------------------------------------------------------
    // Pull the converged intermediate stress back to reference PK2 stress.
    //
    //     S = Fp^-1 Se Fp^-T.
    // -------------------------------------------------------------------------
    Mat3 stress_tensor = result.point.Fp_inv
                       * result.point.Se
                       * result.point.Fp_inv.transpose();
    stress_tensor = Precision(0.5) * (stress_tensor + stress_tensor.transpose());
    result.stress = VolumeStress(stress_tensor);

    // -------------------------------------------------------------------------
    // Store the converged physical history.
    //
    //     Cp_{n+1} = Fp_{n+1}^T Fp_{n+1}
    //     alpha_{n+1} = alpha_n + dgamma.
    // -------------------------------------------------------------------------
    Mat3 Cp_new = result.point.Fp.transpose() * result.point.Fp;
    Cp_new = Precision(0.5) * (Cp_new + Cp_new.transpose());

    // J2 flow is isochoric and therefore det(Cp)=1 analytically. Normalize only
    // the tiny determinant drift accumulated by floating-point tensor algebra.
    const Precision determinant = Cp_new.determinant();
    logging::error(std::isfinite(determinant) && determinant > Precision(0),
        "J2: plastic metric lost positive determinant");

    Cp_new /= std::cbrt(determinant);
    Cp_new = Precision(0.5) * (Cp_new + Cp_new.transpose());

    state[0] = Cp_new(0, 0);
    state[1] = Cp_new(1, 1);
    state[2] = Cp_new(2, 2);
    state[3] = Cp_new(1, 2);
    state[4] = Cp_new(0, 2);
    state[5] = Cp_new(0, 1);
    state[6] = result.alpha_old + result.x(5);

    return result;
}

/**
 * @brief Builds the consistent analytical finite-strain algorithmic tangent.
 *
 * The converged local return map is defined implicitly by
 *
 *     R(x, E) = 0.
 *
 * Linearization gives
 *
 *     R_x dx + R_E dE = 0
 *
 * and therefore
 *
 *     dx/dE = -R_x^-1 R_E.
 *
 * The PK2 stress depends on both E and the converged local unknown x,
 *
 *     dS = S_E dE + S_x dx.
 *
 * Substitution yields the exact consistent tangent of the discrete return map,
 *
 *     C_alg = dS/dE
 *           = S_E - S_x R_x^-1 R_E.
 *
 * S_E, S_x, R_E and R_x are all obtained from directional_response(), which
 * analytically differentiates the complete tensor chain including the exact
 * Fréchet derivative of exp(A). No finite differences are used in this function.
 *
 * @param base Converged finite-strain return-map response.
 * @param shear Elastic shear modulus G.
 * @param bulk Elastic bulk modulus K.
 * @param yield_curve Piecewise-linear isotropic hardening law.
 * @return Consistent six-by-six PK2 / Green-Lagrange material tangent.
 */
Mat6 tangent_finite(const FiniteResponse& base,
                    Precision shear,
                    Precision bulk,
                    const YieldCurve& yield_curve) {
    Mat6 stress_E   = Mat6::Zero();
    Mat6 residual_E = Mat6::Zero();

    // -------------------------------------------------------------------------
    // Build the partial derivatives with respect to total Green-Lagrange strain
    // while holding the local return-map unknown x fixed.
    //
    // Since
    //
    //     C = I + 2 E,
    //
    // each unit VolumeStrain direction dE maps to
    //
    //     dC = 2 dE.
    // -------------------------------------------------------------------------
    for (Index column = 0; column < 6; ++column) {
        VolumeStrain strain_direction;
        strain_direction.voigt().setZero();
        strain_direction.voigt()(column) = Precision(1);

        const Mat3 dC = Precision(2) * strain_direction.tensor();

        const DirectionalResponse derivative = directional_response(
            base.point,
            base.C,
            base.Fp_old,
            base.alpha_old,
            base.x,
            dC,
            Mat3::Zero(),
            Precision(0),
            shear,
            bulk,
            yield_curve,
            base.plastic
        );

        stress_E.col(column) = derivative.d_stress.voigt();

        if (base.plastic) {
            residual_E.col(column) = derivative.d_residual;
        }
    }

    // Elastic states have no active local plastic unknowns. The partial stress
    // derivative at fixed history is already the complete material tangent.
    if (!base.plastic) {
        return stress_E;
    }

    // -------------------------------------------------------------------------
    // Plastic state: assemble R_x and S_x and eliminate the local unknowns by the
    // implicit-function theorem.
    // -------------------------------------------------------------------------
    const LocalLinearization local = local_linearization(
        base.point,
        base.C,
        base.Fp_old,
        base.alpha_old,
        base.x,
        shear,
        bulk,
        yield_curve
    );

    Eigen::FullPivLU<Mat6> lu(local.residual_x);
    logging::error(lu.isInvertible(),
        "J2: singular local Jacobian during consistent tangent evaluation");

    // Do not symmetrize the result artificially. For associative J2 plasticity
    // with isotropic elasticity, symmetry must emerge from the consistent
    // derivative itself. Explicit symmetrization would only hide an error in the
    // constitutive linearization.
    return stress_E - local.stress_x * lu.solve(residual_E);
}
