/**
 * @file register_surface.inl
 * @brief Registers Abaqus *SURFACE definitions for element- and node-based regions.
 *
 * Element-based Abaqus surfaces are converted directly into FEMaster surface
 * and line regions by resolving element sets or individual element identifiers
 * together with the supplied face label. Internal surface identifiers are
 * generated by `model::Model::set_surface()` and therefore do not participate
 * in the allocation pass.
 *
 * Node-based Abaqus surfaces are intentionally represented as ordinary FEMaster
 * node sets under the surface name. This matches the existing FEMaster APIs that
 * already accept node regions where a node-based surface representation is
 * required. Optional Abaqus nodal area/weight values are parsed but are not
 * stored because `NodeRegion` contains identifiers only.
 *
 * @see model::Model::set_surface
 * @see model::NodeRegion
 * @see model::SurfaceRegion
 *
 * @author Finn Eggers
 * @date 17.08.2026
 */

#pragma once

#include <stdexcept>
#include <string>

#include "../../dsl/condition.h"
#include "../../dsl/keyword.h"
#include "../../dsl/registry.h"
#include "../../../core/types_num.h"
#include "../../../model/model.h"

namespace fem::io::reader::commands_abq {

/**
 * Registers the supported Abaqus `*SURFACE` forms.
 *
 * `TYPE=ELEMENT` is the default and accepts an element-set name or individual
 * element identifier followed by a face label such as `S1`. Shell labels
 * `SPOS` and `SNEG` are mapped to FEMaster sides 1 and 2 respectively.
 *
 * `TYPE=NODE` accepts an existing node-set name or individual node identifier.
 * The resulting identifiers are copied into the FEMaster node set named by the
 * Abaqus `NAME` parameter. The optional associated area or distributing weight
 * is consumed but intentionally discarded.
 *
 * Analytical, cutting, Eulerian and XFEM surface definitions are not registered
 * by this reader and therefore remain unsupported input.
 *
 * @param registry Stage-local DSL registry.
 * @param model FEMaster model receiving the generated regions.
 */
inline void register_surface(fem::io::dsl::Registry& registry, model::Model& model) {
    registry.command("SURFACE", [&](fem::io::dsl::Command& command) {
        command.allow_if(fem::io::dsl::Condition::parent_is("ROOT"));
        command.doc("Define an Abaqus element- or node-based surface region.");

        // Restrict the command to the two Abaqus surface forms represented by
        // existing FEMaster surface and node regions
        command.keyword(
            fem::io::dsl::KeywordSpec::make()
                .key("NAME")
                    .required()
                    .doc("Abaqus surface name")
                .key("TYPE")
                    .optional("ELEMENT")
                    .allowed({"ELEMENT", "NODE"})
                    .doc("Surface representation")
        );

        // Activate the FEMaster region that represents the current Abaqus
        // surface before its data lines are consumed
        command.on_enter([&model](const fem::io::dsl::Keys& keys) {
            const std::string& name = keys.raw("NAME");
            const std::string& type = keys.raw("TYPE");

            if (type == "NODE") {
                model._data->node_sets.activate(name);
                return;
            }

            auto surfaces = model._data->surface_sets.activate(name);
            auto lines    = model._data->line_sets.activate(name);
            surfaces->sorted(true).duplicates(false);
            lines->sorted(true).duplicates(false);
        });

        // Convert element-set or element-id face definitions into FEMaster
        // geometric surface entities with automatically assigned internal ids
        command.variant(fem::io::dsl::Variant::make()
            .when(fem::io::dsl::Condition::key_equals("TYPE", {"ELEMENT"}))
            .segment(fem::io::dsl::Segment::make()
                .range(fem::io::dsl::LineRange{}.min(1))
                .pattern(fem::io::dsl::Pattern::make()
                    .one<std::string>().name("TARGET").desc("Element set or element identifier")
                    .one<std::string>().name("SIDE").desc("Abaqus face label, e.g. S1, SPOS or SNEG")
                )
                .bind([&model](const std::string& target, const std::string& side_token) {
                    int side = 0;
                    if (side_token == "SPOS") {
                        side = 1;
                    } else if (side_token == "SNEG") {
                        side = 2;
                    } else if (side_token.size() > 1 && side_token[0] == 'S') {
                        side = std::stoi(side_token.substr(1));
                    } else {
                        side = std::stoi(side_token);
                    }

                    if (model._data->elem_sets.has(target)) {
                        model.set_surface(target, static_cast<fem::ID>(side));
                        return;
                    }

                    std::size_t parsed = 0;
                    const long value = std::stol(target, &parsed);
                    if (parsed != target.size()) {
                        throw std::runtime_error("SURFACE target '" + target + "' is not an element set or element id");
                    }
                    model.set_surface(-1, static_cast<fem::ID>(value), static_cast<fem::ID>(side));
                })
            )
        );

        // Store node-based Abaqus surfaces directly as ordinary FEMaster node
        // sets. Existing source sets are copied; individual node ids are added
        // directly to the currently active destination set.
        command.variant(fem::io::dsl::Variant::make()
            .when(fem::io::dsl::Condition::key_equals("TYPE", {"NODE"}))
            .segment(fem::io::dsl::Segment::make()
                .range(fem::io::dsl::LineRange{}.min(1))
                .pattern(fem::io::dsl::Pattern::make()
                    .one<std::string>().name("TARGET").desc("Node set or node identifier")
                    .one<fem::Precision>().name("AREA").desc("Ignored Abaqus nodal area/weight")
                        .on_missing(fem::Precision{1}).on_empty(fem::Precision{1})
                )
                .bind([&model](const std::string& target, fem::Precision area) {
                    (void) area;

                    auto destination = model._data->node_sets.get();
                    if (!destination) {
                        throw std::runtime_error("SURFACE TYPE=NODE has no active destination node set");
                    }

                    if (model._data->node_sets.has(target)) {
                        auto source = model._data->node_sets.get(target);
                        if (source != destination) {
                            destination->add(*source);
                        }
                        return;
                    }

                    std::size_t parsed = 0;
                    const long value = std::stol(target, &parsed);
                    if (parsed != target.size()) {
                        throw std::runtime_error("SURFACE target '" + target + "' is not a node set or node id");
                    }
                    destination->add(static_cast<fem::ID>(value));
                })
            )
        );
    });
}

} // namespace fem::io::reader::commands_abq
